### PR TITLE
Add duosecurity.com to yellowlist

### PR DESCRIPTION
**Pull request by mattcallanan**
Attempting to fix https://github.com/EFForg/privacybadger/issues/1102

### CODE REVIEW

**Comment by ghostwords** [comment]
Hello and thank you for the PR!

I take this to mean that setting `duosecurity.com` domains to "yellow" does work around the problem, at least in some cases. (I previously received reports that it does not.)

Could you provide an example or two of pages where I could see the Duo iframe in action?

Could you also please provide the [debugging output](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for "duosecurity"?

**Comment by ghostwords** [comment]
t@mattcallanan Could you look into the questions above?

**Comment by ghostwords** [comment]
@mattcallanan Could you look into the above questions please?

**Comment by mattcallanan** [comment]
Hi @ghostwords, I can confirm that toggling `api-*.duosecurity.com` to yellow in PB Chrome extension popup does work around the problem.

Debug output captured while duosecurity.com is blocked (red):

```
**** ACTION_MAP for duosecurity.com
api-f4ecbba1.duosecurity.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1550011213793,
  "userAction": ""
}
duosecurity.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
**** SNITCH_MAP for duosecurity.com
duosecurity.com [
  ... lists 3 corporate domains
```

I'd prefer not to post internal screenshots here.  Please let me know if you need more details and if so the best way to submit off-list.

thanks,
-Matt

**Pull request merged**
