### PR TITLE
When using Firefox, add an iframe to put the export settings link in

### LINKED ISSUE #1674: Export user data doesn't open file download dialog in Firefox
When clicking Export user data it opens an other tab with a long URL, no file will be downloaded.

### PR DESCRIPTION
**Pull request by kenjiO**
I was able to fix #1674 on my mac firefox 57.0.1 by doing this.  I ran the unit tests and it pasts but I wasn't able to get the functional tests working on my computer so I don't know if those will pass or not.  Can you let me know if you think this is a good fix or if you have suggestions on modifying it?

### CODE REVIEW

**Comment by ghostwords** [comment]
Cool, thank you! I'll take a look in a bit.

Regarding functional tests, no problem. If there is something broken or unclear in our [guide to setting up tests](https://github.com/EFForg/privacybadger/blob/master/doc/tests.md), I would like to know though.

**Comment by ghostwords** [comment]
Hi sorry, I haven't been able to review this yet. Should happen early next week.

**Comment by ghostwords** [comment]
This looks like a good workaround for the Firefox bug. My main concern is that of readability: We are adding a workaround (create an iframe to fix the file download dialog) to an existing workaround (use data instead of blob URIs on Firefox), and it seems that it can be hard to tell where one workaround ends and another begins.

One way to make it easier to follow is to move iframe creation into a function, something like `addDataURIDownloadWorkaroundForFirefox`. How does that sound?

Sorry it took me a while to get to this!

**Comment by ghostwords** [comment]
@andresbase Could you check that we improved data exporting in Firefox on Android with this patch?

**Comment by lemnis** [comment]
@ghostwords I did not test it, but in the bugzilla thread is mentioned that blob: works inside an iframe. Removing the necessity of the previous workaround, so quiet possible beneath code could work:

```js
var a = document.createElement('a');
a.setAttribute('download', filename || '');

var blob = new Blob([mapJSON], { type: 'application/json' }); // pass a useful mime type here
a.href = URL.createObjectURL(blob);

function cb() {
  a.dispatchEvent(new MouseEvent('click'));
  URL.revokeObjectURL(blob);
}

//TODO no longer need the following iframe when https://bugzilla.mozilla.org/show_bug.cgi?id=1379960 is fixed
// Create or use existing iframe for the 'a' element
if (chrome.runtime.getBrowserInfo) {
  chrome.runtime.getBrowserInfo((info) => {
    if (info.name == "Firefox") {
      var iframe = document.getElementById('exportUserDataIframe');
      if (!iframe) {
        iframe = document.createElement('iframe');
        iframe.id = "exportUserDataIframe";
        iframe.setAttribute("style", "visibility: hidden; height: 0; width: 0");
        document.getElementById('export').appendChild(iframe);

        iframe.contentWindow.document.open();
        iframe.contentWindow.document.write('<html><head></head><body></body></html>');
        iframe.contentWindow.document.close();
      } else {
        // Remove the old 'a' element from the iframe
        var oldElement = iframe.contentWindow.document.body.lastChild;
        iframe.contentWindow.document.body.removeChild(oldElement);
      }
      iframe.contentWindow.document.body.appendChild(a);
      cb();
    } else { cb (); }
  });
} else {
  cb();
}
```

**Comment by kenjiO** [comment]
I made some updates based on the feedback.  Since it turns out the iFrame workaround I originally had to fix the data URL download workaround also fixes the blob issue I just removed the data URL workaround and used the iFrame to fix the blob issue.   According to [bugzilla 1420419](https://bugzilla.mozilla.org/show_bug.cgi?id=1420419) the blob issue with firefox is not fixed until Firefox 59 so I changed the comment to indicate the workaround is neccesary until firefox 58 goes away instead of firefox 52.

**Pull request merged**
