### PR TITLE
WIP embedded tweet widget

### PR DESCRIPTION
**Pull request by cowlicks**
This code dynamically creates a sandbox for an embedded tweet. In the sandbox there is no access to the external dom, info about the origin, or localstorage, or cookies, etc.

todo:
* finish the resizing stuff so the tweet will get sized based on its surrounding content
* hook into webrequests so that we catch the embedded tweet before it can request it's scripts

### CODE REVIEW

**Comment by cowlicks** [comment]
I'm ending this work for now. Twitter's `widgets.js` includes analytics and tracking, but also functionality for sites, like dynamically loading tweets. I may come back to this eventually to:
* try including code to block `widget.js`'s tracking, while letting it do its real work
* maybe someone will make an OSS replacement to `widgets.js`'s we can use

**Comment by cowlicks** [comment]
As it is now, this currently does a great job of injecting the tweet into a sandboxed iframe.

**Comment by cowlicks** [comment]
Err it looks like since I force pushed after closing the PR, the commits don't get included here. Here is a link to the branch: https://github.com/cowlicks/privacybadgerchrome/tree/gh-1391

**Comment by ghostwords** [comment]
See https://github.com/EFForg/privacybadger/issues/1552#issuecomment-336942508.

**Pull request closed without merging**
