### PR TITLE
Fix incognito sliders in firefox

### LINKED ISSUE #1060: Badger's popup broken in Firefox Private Browsing (Incognito) windows
I am not able to see any sliders when I am using a private window, a.k.a. incognito mode, in Firefox.
I have tested multiple sites to verify.
Firefox 50.1.0 (I just updated from 49 and the issue is still present.)
Add-ons: HTTPS Everywhere, NoScript, uBlock Origin, Stylish, Reddit Enhancement Suite, Privacy Badger.
I don't believe this was an issue yesterday and I haven't made any changes beyond updating after discovering the error.
I appreciate any assistance you may be able to provide.

### PR DESCRIPTION
**Pull request by cowlicks**
Fixes #1060.

### CODE REVIEW

**Comment by ghostwords** [comment]
Edited description to link to the original issue (https://github.com/EFForg/privacybadger/issues/1060).

**Comment by ghostwords** [comment]
Does this address the options page, broken for the same reasons as the popup in Firefox? To ask in a different way, if the user opens Badger's popup in an Incognito window, and clicks on the options button, what happens?

**Comment by cowlicks** [comment]
@ghostwords No, the options page is still broken the same way it is on master.|

That should be addressed (in a seperate PR) by opening a tab in a non-incognito window, which mimics chrome's behavior.

**Comment by ghostwords** [comment]
This may or may not have an impact on #1475.

**Comment by cowlicks** [comment]
Test for all of this have been added.

**Comment by ghostwords** [comment]
@cowlicks Could you rebase on master and resolve conflicts please?

**Comment by cowlicks** [comment]
@ghostwords done

**Comment by ghostwords** [comment]
The popup fails to populate on seemingly ever page because of JavaScript errors for me. Screenshot:

screenshot from 2017-08-21 20 53 55

**Comment by cowlicks** [comment]
@ghostwords that's from the rebase, I'll take a look tomorrow. Otherwise the code is ready to review.

**Comment by cowlicks** [comment]
@ghostwords should be fixed now

**Comment by ghostwords** [comment]
We seem to have a rendering/performance issue in Firefox. Compare opening the popup on a typical news site in Firefox using Privacy Badger from this branch vs. from master.

I see a noticeable delay (and a jump) between the popup appearing and the popup being populated with data, as opposed to the popup opening relatively smoothly in one render with the domains list progressively rendering within.

If the delay is unavoidable, we should add a loading spinner to the "body" section of the popup (below the version number and above the three buttons in the footer).

**Comment by ghostwords** [comment]
As previously noted, the options page button in Incognito windows takes you to a broken options page. Could we fix it to open the options page in a non-Incognito window in this PR? It seems disappointing (the opposite of delightful ...) to fix most of the popup without fixing all of the popup.

**Comment by cowlicks** [comment]
Most of the lag seems to be from `requestAnimationFrame`, not from the message passing. I dropped some prints inside the popup and message passing code, and around request animation, and got this https://gist.github.com/cowlicks/e40982d606553a885530e1694c22456a

I'll see how much reducing calls to `requestAnimationFrame` helps.

**Comment by ghostwords** [comment]
I am not sure we are looking into the same thing ... I am talking about the delay between when you see the popup showing "Privacy Badger detected potential trackers ..." and the domain toggle legend icons but no domain list, and when you see "Privacy Badger detected 40 potential trackers ..." and the domain list start to get progressively rendered.

Here is what the popup looks like for a noticeable split second for me (noticeable in Firefox, not Chrome probably because of browser performance):
screenshot from 2017-08-24 18 54 51

This seems like a regression from production Privacy Badger.

**Comment by cowlicks** [comment]
@ghostwords I've fixed the issue with the loading the icons by having them rendered right before the first origin is ready to render [here]().

I've also dramatically improved the performance of the popup for many domains. The issue was not requestAnimationFrame, or messaging. It was that we were rendering the domains in a recursive function, AND passing in needed variables from each functions outer scope. So the inner function calls were depending all the outer scopes.

I fixed this by un-nesting the functions, and passing their arguments in explicitly. Now the popup loads large domain lists smoothly and quickly.

I also removed the need to send a message for every origin in the popup by adding `getAllOriginsWithActionsFromTab`.

**Comment by ghostwords** [comment]
Sounds good! Unfortunately I now see consistent undesirable resizing behavior in Firefox. The popup starts out smaller than it needs be and gets resized a split second later. GIF below:

test

**Comment by cowlicks** [comment]
@ghostwords options page now opens in non-incognito window.

I changed the chunk size to make the resizing more smooth, and less chunky. Are you asking that I make the popup so it isn't resized in this PR?

**Comment by ghostwords** [comment]
Replaced by #1899.

**Pull request closed without merging**
