### PR TITLE
Fix replacement widget creating zero-width styles

### PR DESCRIPTION
**Pull request by twome**
This uses .offsetWidth instead of .clientWidth(), and then subtracts the border width to get a better approximation of the original element's dimensions. It also checks to make sure we got dimensions that makes sense (>0px) before adding width/height rules to the replacement element.

### CODE REVIEW

**Comment by ghostwords** [comment]
Hello and thank you for the PR! Could you provide examples of what this patch fixes?

**Comment by twome** [comment]
`.clientWidth` and `.clientHeight` have the very unintuitive behaviour of returning 0 for all inline elements (which I'm pretty sure iframes are by default), so for most situations, the replacement widget was getting assigned a `width` and `height` of "0px", which doesn't make much sense when we're also specifying a `min-width`/`min-height`. 

By removing the `width`/`height` rules entirely, the iframe can either a) use its default browser width (which makes the most sense if we have no information on how to properly display it), or b) be styled according to selectors such as `.container iframe`.

Switching to `offsetWidth` returns useful dimensions much more often, because it works on inline elements.

[My personal website](twome.name) has a simple example of this - the iframe can receive a `width: 100%` rule when the element `width` style is removed, and the lazy-loading effect is ruined by the replacement appearing regardless of the visual state of the original iframe.

---

To extend this a bit off-topic: would you be open to the idea of not showing the replacement widget at all if the iframe it's replacing is visually hidden, whether with `display: none`, `visibility: hidden`, width/height of 0 etc? 

- Currently, lazy-loaded iframe layouts are breaking, especially if the page's code relies on the original iframe having certain attributes / dimensions. 
- Conversely, there could be at least one downside. Although the sandboxing between iframes and parent frames severely limits the usefulness of invisible iframes, invisible autoplaying audio iframes might be something users want to know is missing (although *where* such an iframe would be placed in the DOM could make an in-place replacement widget look disastrous).

Ideally, this would be an opt-in setting with a low precedence in the options UI; just a nicety for power users.

**Comment by ghostwords** [comment]
Thanks for the explanation and sorry for the delay!

I pulled in your fixes in a7782fbea7b4eb20d03fef7b59800bc4d6d2a197 as part of the latest widget replacements improvements PR. Let me know if you notice any issues please.

**Comment by ghostwords** [comment]
>would you be open to the idea of not showing the replacement widget at all if the iframe it's replacing is visually hidden...

Do you have any examples of this problem? I'm aware of some sites that use custom widget loading implementations that we don't handle correctly. Which, from what I've seen, results in:
- Our placeholders not finding any expected elements to replace, meaning no placeholder at all
- Placeholder activation buttons being inoperable due to our placeholder being overlaid by some invisible page element that captures clicks before they get to our button. (This case seems rare.)
- Post activation button click, us failing to find any expected script elements to reinsert into the page (in the case of widgets like Disqus that require their script tag to be rerun). This looks the same as the previous case: clicking our buttons doesn't do anything.

**Comment by ghostwords** [comment]
I was thinking part of the solution for the above range of the problems would be to add widget controls to the popup. So that if something is broken on the page, users who visit the popup can at least see what was supposed to happen and do something about it.

I'm not sure I'm talking about quite the same problem as you though.

**Pull request closed without merging**
