### PR TITLE
Change twitter share message to correctly point to the EFF account

### LINKED ISSUE #1620: Change text of the Tweet on the firstRun page
https://github.com/EFForg/privacybadger/blob/a1bc52444843a6a00c0c57d8b138b4ee2c891ef0/src/skin/firstRun.html#L68

From Soraya:

I just met with a-team, and we wanted to request a few changes to the default tweet that comes from installing Privacy Badger.

The original:

"I just installed Privacy Badger, a new tool from EFF to stop companies from spying on your browsing habits - https://eff.org/privacybadger"

Change to:

"I just installed Privacy Badger, a new tool from @EFF to stop companies from spying on your browsing habits https://eff.org/privacybadger"
(add the @ before EFF, remove the hyphen)

Rainey asks:

After people tweet, is there a way to have a "suggested" account which prompts them to follow EFF?

### PR DESCRIPTION
**Pull request by andresbase**
Resolves #1620.

From a ticket to change:
"I just installed Privacy Badger, a new tool from EFF to stop companies
from spying on your browsing habits - https://eff.org/privacybadger"
to
"I just installed Privacy Badger, a new tool from @EFF to stop companies
from spying on your browsing habits https://eff.org/privacybadger"

Therefor adding "@" and removing "-"

### CODE REVIEW

**Comment by ghostwords** [comment]
Edited description to link to and autoresolve originating issue.

**Comment by ghostwords** [comment]
I think we have a problem: `&related=eff` makes for a broken link (screenshot below). Was it supposed to be `?related=eff`?

screenshot from 2017-09-01 12 16 04

**Comment by andresbase** [comment]
That's weird, when I test it works normally:
screenshot_2017-09-01_09-27-33
The related is in the url

screenshot_2017-09-01_09-25-12
Takes you to twitter with the default text

screenshot_2017-09-01_09-23-57
Tweet is posted successfully

screenshot_2017-09-01_09-25-35
Clicking on the URL takes you to our site

**Comment by ghostwords** [comment]
Ah, sorry, false alarm. I overlooked that the Twitter URL has two parameters, not one.

**Pull request merged**
