### PR TITLE
Make Clickable Region More Consistent

### PR DESCRIPTION
**Pull request by jalcine**
This is a slight UX fix; ensuring a consistent presented click region
with no weird cursor jumping.

### CODE REVIEW

**Comment by ghostwords** [comment]
Hello and thank you for the PR! Does this fix #1912 and/or #1746?

**Comment by jalcine** [comment]
This PR addresses https://github.com/EFForg/privacybadger/issues/1912. I’ll have to look into https://github.com/EFForg/privacybadger/issues/1746 because this change actually prohibits the tool-tip from showing at all. I’ll look more closely into that.

(Originally published at: https://v2.jacky.wtf/post/b40fe6e3-99ac-4928-b643-d4c35c78d06b)

**Comment by jalcine** [comment]
Looking more into https://github.com/EFForg/privacybadger/issues/1746 and at the DOM currently, the `&lt;label&gt;` and `&lt;div .ui-slider&gt;` bits are weirdly laid out causing that aforementioned bug. I’m looking to see if there’s a simple fix for this. To be honest, just _deleting_ `.ui-slider-horizontal` fixes this completely.

(Originally published at: https://v2.jacky.wtf/post/6ff99ed5-19f2-4bbf-9e95-d4e55007249a)

**Comment by jalcine** [comment]
The change in https://github.com/EFForg/privacybadger/pull/2345/commits/d73c651eb680e9367630ab0a3bc319fcf2293d63 will handle https://github.com/EFForg/privacybadger/issues/1912 and https://github.com/EFForg/privacybadger/issues/1746. The magic of just not displaying anything, heh!

(Originally published at: https://v2.jacky.wtf/post/fe558e79-0bf5-4086-aa8f-3accb162a1e2)

**Pull request closed without merging**
