### PR TITLE
Don't inject socialwidgets.css until it is needed.

### PR DESCRIPTION
**Pull request by cowlicks**

### CODE REVIEW

**Comment by ghostwords** [comment]
Addresses part of #931.

**Comment by ghostwords** [comment]
What URLs did you use to test? (I don't think we have any automated tests for widget replacement, unfortunately ...)

**Comment by cowlicks** [comment]
example here https://dev.twitter.com/web/tweet-button

**Comment by cowlicks** [comment]
Do you know of others? I'll start saving them.

**Comment by cowlicks** [comment]
Anything else?

**Comment by ghostwords** [comment]
I just haven't gotten to this yet, sorry. We need to gather more examples to test against, I need to review the code and verify we haven't introduced new breakages.

**Comment by cowlicks** [comment]
Here are more sites, they display the buttons as expected. To verify this css is not injected you can visit a page, like [github.com](https://github.com) and check the sources in the devtools to see socialwidgets.css is not there.

Facebook like button:
https://developers.facebook.com/docs/plugins/like-button
https://adf.ly/

google buttons:
https://developers.google.com/+/web/+1button/

add this:
https://www.state.gov/p/af/index.htm
http://www.cambridge.org/

**Comment by ghostwords** [comment]
Thanks for the links and for the PR! I don't think this introduces any new issues while avoiding needless resource injection. Merging.

**Comment by ghostwords** [comment]
Not sure why this wasn't marked as merged. I merged manually using the CLI, but up to now, this always worked to mark PRs as merged.

**Pull request closed without merging**
