### PR TITLE
Add migration to fix yellowlisted yet blocked domains

### LINKED ISSUE #1466: PB blocks avatars[0123].githubusercontent.com
PB blocks `avatars[0123].githubusercontent.com` (red slider). I just noticed this in the past couple days. The problem description is similar to fixed issue https://github.com/EFForg/privacybadger/issues/443.

### LINKED ISSUE #1469: disqus.com
Disqus comment sections on websites will not load and when visiting disqus.com the entire site fails to load.

Privacy Badger is blocking c.disquscdn.com.

Screenshot of disqus.com:
screenshot_2017-07-01_10-59-34

Screenshot of disqus.com with Privacy Badger popup:
screenshot_2017-07-01_11-02-35

### LINKED ISSUE #1494: PB blocks *.cloudfront.net
PB seems to block `*.cloudfront.net`, which many sites use as a CDN, so this problem breaks multiple sites. One example is the AWS console at https://console.aws.amazon.com which renders almost entirely blank for me.

### LINKED ISSUE #1495: PB blocks fonts.googleapis.com
PB blocks `fonts.googleapis.com` which causes rendering problems on some sites. One place you can see the problem is in the table at the bottom of https://google.github.io/material-design-icons/ .

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #1466, fixes #1469, fixes #1494, fixes #1495.

Follows up on #1482.

### CODE REVIEW

**Comment by ghostwords** [comment]
To add to https://github.com/EFForg/privacybadger/issues/1474#issuecomment-314825678, yellowlist domain removal logic marked subdomains (`camo.githubusercontent.com`) of each removed domain (`githubusercontent.com`) as blocked if they were in `action_map` (regardless of their heuristicAction), while yellowlist domain addition logic marked blocked domains (`githubusercontent.com`) and their base domains as "cookieblocked", but didn't do anything about the subdomains.

This PR should fix the affected subdomains by looking for blocked, yellowlisted domains and then fixing their status to one of "cookieblock", "allow" or "", depending on `snitch_map` contents.

**Comment by cowlicks** [comment]
I restarted the failing travis job. I'll merge if it passes.

**Comment by ghostwords** [comment]
Note that this is still not a perfect reversal of the incident:
- Previously non-tracking domains (not their basedomains which this PR addresses) on the yellowlist are now yellowlisted. Not too worried about this one.
- Current yellowlist domain removal logic blocked domains if they *ended with* the removed domain. Which is different from being the removed domain's subdomain ...

**Comment by ghostwords** [comment]
Looking through error reports, looks like we do have some substring-blocked domains, for example, `jse.trivago.com` (because of `go.com`), `onesignal.com` (because of `al.com`), `appleid.cdn-apple.com` (because of `apple.com`). I'll update the migration to cover all of these too.

**Comment by ghostwords** [comment]
I expanded the scope of the migration to try to undo everything we might have blocked by mistake when we blanked out people's yellowlists.

The updated migration goes through every blocked domain and checks if the domain (`jse.trivago.com`) ends with any yellowlisted domains (`go.com`). If it does, we check `snitch_map` to see if we have no entries (`heuristicAction` becomes ""), one or two entries (`heuristicAction` becomes "allow"), or three or more entries.

If we have three or more entries in `snitch_map`, we call `blacklistOrigin`, which takes care of updating the domain and its base domain either to "block" or "cookieblock".

If there are bugs in this logic, I expect they would be in the direction of unblocking too much, which should be OK since Badger will relearn to block as necessary.

**Comment by cowlicks** [comment]
Question: What is the policy for subdomains of domains on the CBL? What is the policy of parent domains on the CBL? What is the policy when a domain on the CBL is also in the PSL?

I think the answer to this should be documented somewhere.

Reviewing now.

**Comment by ghostwords** [comment]
When we block a domain (the correct way, via [blacklistOrigin](https://github.com/EFForg/privacybadger/blob/ae8e2e565ad1e2197210573c409289991ee5e3c7/src/js/heuristicblocking.js#L61)) now, we "cookieblock" the domain (instead of blocking) when the domain, or any of its subdomains down to the base domain are on the yellowlist. We also "cookieblock" those subdomains.

When we [add a domain to the yellowlist](https://github.com/EFForg/privacybadger/blob/ae8e2e565ad1e2197210573c409289991ee5e3c7/src/js/background.js#L310) and its base domain is already blocked or cookieblocked, we cookieblock that domain right away.

So, subdomains of yellowlisted domains should end up getting "cookieblocked".

**Comment by ghostwords** [comment]
The PSL is used when we get the base domain. The base domain of `ajax.googleapis.com` is `ajax.googleapis.com`, not `googleapis.com`, because `googleapis.com` is on the PSL.

**Comment by ghostwords** [comment]
However, `blacklistOrigin` calls `utils.explodeSubdomains` with `true` for the second arg,
 [which avoids using the PSL](https://github.com/EFForg/privacybadger/blob/ae8e2e565ad1e2197210573c409289991ee5e3c7/src/js/utils.js#L69) ... meaning blocking `fonts.googleapis.com` ends up cookieblocking the domain even though its base domain (`fonts.googleapis.com`) is not on the yellowlist.

**Comment by ghostwords** [comment]
Some bits use the PSL, some do not; the various bookkeeping structures can drift apart; importing data loses `snitch_map` state for non-""/"allow" `heuristicAction` domains ...

**Comment by cowlicks** [comment]
I think there is a problem.

If we have a site on the cookieblock list like `consent.google.com`, with 3 snitch map entries. Then we also have a site like `google.com`. Suppose they are both blocked. When we run this migration, `google.com` may either be blocked, or unblocked, depending on the order.

If `google.com` is run first, then it will get blocked later when `consent.google.com` is put through `blacklistOrigin`. If it is run 2nd, it will be unblocked.

Is this correct? If so which way should it be?

**Comment by ghostwords** [comment]
- We don't actually have `google.com` in the yellowlist.
- Have you been able to reproduce this issue in your testing?
- If this is indeed an issue (still need to figure out if it is), is the fallout of this edge case that a base domain may stay incorrectly blocked? Meaning we still fix all these other domains except for this one edge case.
- How many domains on the yellowlist might actually be affected by this?

**Comment by ghostwords** [comment]
Wouldn't `setupSubdomainsForCookieblock` take care of this? The function loops over every yellowlisted domain (`cse.google.com`, etc.), gets its base domain (`google.com`) and compares it to the passed-in base domain (`google.com`). If they are equal, the base domain gets cookieblocked.

**Comment by cowlicks** [comment]
@ghostwords ah yeah you are correct. 

It seems like there would still be an issue, should it be cookieblocked or noaction/allow?

**Comment by ghostwords** [comment]
As I wrote above, previously non-tracking, yellowlist-associated domains are now yellowlisted for affected Badgers. I think this is OK, something that we can deal with later, if it actually becomes an issue.

**Comment by cowlicks** [comment]
@ghostwords with the current PR as-is, we don't know if the domain would be set to noaction/allow or cookieblock. It depends on the order that these get run in.

**Comment by ghostwords** [comment]
Both are acceptable, although have you verified this actually happens? See my comments above please.

**Comment by cowlicks** [comment]
I realize that both are better than incorrectly blocked. However I'd like it to be at least deterministic. Can we just decide on one to be correct and go with that?

I'm working on verifying this issue.

**Comment by cowlicks** [comment]
@ghostwords do you still plan on adding tests?

**Comment by ghostwords** [comment]
I did, here: https://github.com/EFForg/privacybadger/issues/1515#issuecomment-316502114

**Pull request merged**
