### PR TITLE
Create messages.json

### PR DESCRIPTION
**Pull request by Clonewayx**
Translate to Czech

### CODE REVIEW

**Comment by cowlicks** [comment]
Thank you! I *think* that translations are handled on the [transifex site](https://www.transifex.com/eff/privacy-badger/). So the maintainers might add these there, instead of merging here.

**Comment by cowlicks** [comment]
Oh! I looked at previous PR's, and it seems translations *can* be merged here. Sorry for the noise.

**Comment by cooperq** [comment]
Yes, to clarify we don't actually do any translations on transifex (mostly because I have never taken the time to figure out how it works) so this is fine! Thanks!

**Comment by cooperq** [comment]
This looks great! Thanks for the translation!

**Pull request merged**
