### PR TITLE
Added iltalehti to multiDomainFirstParties.js

### PR DESCRIPTION
**Pull request by theel0ja**

### CODE REVIEW

**Comment by theel0ja** [comment]
image

**Comment by ghostwords** [comment]
Is this in the browser where Privacy Badger learned to block `ilcdn.fi`?

**Comment by theel0ja** [comment]
It hasn't been blocked anytime

**Comment by ghostwords** [comment]
Oh! What drove you to reach out to get this fixed then?

**Comment by ghostwords** [comment]
I'm just trying to understand the problem behind this PR better. Feel free to mail me directly at alexei at eff dot org.

**Comment by ghostwords** [comment]
I'm going to close this for now. We don't need to keep track of related domains unless doing so fixes broken sites. Please let me know if I misunderstood something.

**Comment by ghostwords** [comment]
Oh, was it `il.fi` that got blocked by Privacy Badger instead?

**Pull request closed without merging**
