### PR TITLE
Fix error reporting when disabled

### LINKED ISSUE #1475: Investigate NULL block/cookieblock/... broken site/error report submissions
Many error reports have NULL block/cookieblock/... domain state fields. Let's find and fix what's causing this to happen.

A related issue is that we get a lot of nonsense message ("test", "banana", ...) reports. Do the nonsense reports always have NULL domain state fields? Are NULL field reports always nonsense?

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #1475, or at least a big part of it: not reporting any domains on whitelisted pages. Will still have the issue of reporting incomplete domain lists when Badger is used with other blockers.

### CODE REVIEW

**Comment by ghostwords** [comment]
To test error reports, run a [local server that prints POST data](https://gist.github.com/anonymous/1a5d8e60573e71e0a9d0e60c05f934cd) and edit your popup.js to point to your local server. For example, if your server is on port 8080:
```diff
diff --git a/src/js/popup.js b/src/js/popup.js
index 34fd017..7e92b69 100644
--- a/src/js/popup.js
+++ b/src/js/popup.js
@@ -154,7 +154,8 @@ function send_error(message) {
     var out_data = JSON.stringify(out);
     var sendReport = $.ajax({
       type: "POST",
-      url: "https://privacybadger.org/reporting",
+      //url: "https://privacybadger.org/reporting",
+      url: "http://localhost:8080/",
       data: out_data,
       contentType: "application/json"
     });
```
You can also change "POST" to "GET" above so you can use Python's `http.server`, but its output can be hard to read (everything URL encoded and squished on the same line).

**Comment by ghostwords** [comment]
This is ready for testing.

I'll look this over again too later, especially https://github.com/EFForg/privacybadger/pull/1776/commits/401fdceb3fc581f7ae9ab47f951e5d994b1a686c and https://github.com/EFForg/privacybadger/pull/1776/commits/b578fdeac428465606690394ae50f901a2c56329?w=1. Want to review how well we are covered by tests here ... Would messing with the code (say, [here](https://github.com/EFForg/privacybadger/commit/401fdceb3fc581f7ae9ab47f951e5d994b1a686c#diff-f0450b33f099abd6026a2de089706c2cR174) or [here](https://github.com/EFForg/privacybadger/commit/b578fdeac428465606690394ae50f901a2c56329?w=1#diff-f0450b33f099abd6026a2de089706c2cR96) or [here](https://github.com/EFForg/privacybadger/commit/b578fdeac428465606690394ae50f901a2c56329?w=1#diff-f0450b33f099abd6026a2de089706c2cR221)) set off alarms?

**Comment by andresbase** [comment]
# For Posterity
## BEFORE
```
{ 'browser': 'Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 '
             'Firefox/57.0',
  'fqdn': 'www.flightradar24.com',
  'message': 'TEST DIS',
  'url': 'https://www.flightradar24.com/1',
  'version': '2017.11.20'}
```
## AFTER
```
{ 'allow': 'sc.iasds01.com,d.turn.com,sync.search.spotxchange.com,rtb-csync.smartadserver.com,ib.adnxs.com,ads.stickyadstv.com,sync.adaptv.advertising.com,match.adsrvr.org,rtb.openx.net,sync-tm.everesttech.net,sync.mathtag.com,ad.turn.com,x.bidswitch.net,c1.adform.net',
  'block': 'adservice.google.com,securepubads.g.doubleclick.net,googleads.g.doubleclick.net,staticxx.facebook.com,bid.g.doubleclick.net,cm.g.doubleclick.net,googleads4.g.doubleclick.net',
  'browser': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like '
             'Gecko) Ubuntu Chromium/62.0.3202.89 Chrome/62.0.3202.89 '
             'Safari/537.36',
  'cookieblock': 'maps.google.com,platform.twitter.com,apis.google.com,syndication.twitter.com,www.facebook.com,accounts.google.com,www.google.com',
  'fqdn': 'www.flightradar24.com',
  'message': 'Test Dis OK?',
  'noaction': 'cdnjs.cloudflare.com,csi.gstatic.com,www.googletagservices.com,pagead2.googlesyndication.com,connect.facebook.net,ssl.google-analytics.com,maps.gstatic.com,maps.googleapis.com,tpc.googlesyndication.
com,fonts.googleapis.com,fw.adsafeprotected.com,ssl.gstatic.com,dt.adsafeprotected.com,c.betrad.com,s0.2mdn.net,sync.adap.tv,s1.2mdn.net,l.betrad.com,ads.creative-serving.com,fonts.gstatic.com',
  'url': 'https://www.flightradar24.com/1',
  'version': '2017.11.9'}
```

**Comment by ghostwords** [comment]
This PR (released with 2018.1.22) seems to have succeeded in reducing all-NULL report counts:
```
+--------------+----------+---------------+
| version      | all NULL | blank message |
+--------------+----------+---------------+
| 2017.7.24    | 53.93%   | 25.08%        |
| 2017.9.12    | 51.82%   | 16.26%        |
| 2017.9.12.1  | 51.83%   | 24.75%        |
| 2017.10.25.1 | 39.93%   | 15.88%        |
| 2017.11.9    | 41.04%   | 19.73%        |
| 2017.11.20   | 40.84%   | 16.89%        |
| 2018.1.22    | 10.53%   | 18.27%        |
| 2018.1.25    | 5.88%    | 15.05%        |
| 2018.1.30    | 8.85%    | 17.78%        |
| 2018.2.5     | 8.58%    | 16.44%        |
+--------------+----------+---------------+
```

**Pull request merged**
