### PR TITLE
Style remaining popup buttons

### PR DESCRIPTION
**Pull request by ghostwords**
Styled:
- "Submit Error" / "Cancel" buttons on the "Did Privacy Badger break this site?" (broken site report) overlay
- "Copy to clipboard" button on the Share overlay

Updated to inherit from standard Badger button styles:
- Welcome page link on the reminder overlay
- "Tell us" link on the critical error overlay

Overlay close links (in the upper right) are now keyboard-navigable:
- The SVG "X" on the new user welcome page reminder overlay
- The "[X] close" links on the Share/broken site report overlays

This does not fix keyboard navigation issues described in https://github.com/EFForg/privacybadger/pull/2629#issuecomment-646101693.

### CODE REVIEW

**Comment by ghostwords** [comment]
I added a fix for Firefox to close the popup after clicking the options page icon or the welcome page reminder link.

**Comment by ablanathtanalba** [comment]
The code itself all looks good to me, and these are nice bite sized improvements to the overall look.

If you don't mind, here are some more styling suggestions for the places you're currently looking at. Feel free to take or leave them as you like:

In the text input area for reporting a site breakage, I think making the text box a little bigger will make it easier for folks to look at and type in. As it is now they can't see more than one line at a time. It should also look fine on mobile (admittedly I haven't tested that yet). I just added a couple lines to `popup.css`:
```
#error_input {
  ...
  padding: 8px;
  height: 100px;
}
```
Screen Shot 2020-07-02 at 3 38 47 PM




Then I thought it make increase uniformity across the different layers of the popup to make the button stylings a little more uniform. So I tried extending the `pbButton` class to the other buttons in those secondary layers:

Screen Shot 2020-07-02 at 3 48 10 PM


Screen Shot 2020-07-02 at 3 50 06 PM

In the report error & cancel report buttons, I also added the line `width: 120px;` to their css class so that they don't stack on top of each other.



That's all! No worries if you don't like these suggestions or think they're not relevant to this PR.

**Comment by ghostwords** [comment]
Please take a look with:
- Locales that tend to longer-than-English strings (Russian, German, French)
- An RTL locale
- Firefox on Android
- Popup hardcoded to width of 360 pixels

**Comment by ablanathtanalba** [comment]
Ok! Did some testing hitting those points you listed up above. Here's what the error reporting popup view looked like during those visual tests:

<details>
<summary>In Arabic RTL locale: </summary>
‏لقطة الشاشة ٢٠٢٠-٠٧-٠٦ في ٣ ٠١ ٢٦ م

</details>


<details>
<summary>In German on regular screen: </summary>
Bildschirmfoto 2020-07-06 um 3 25 35 PM
</details>


<details>
<summary>In German on 360px screen: </summary>
Bildschirmfoto 2020-07-06 um 3 18 52 PM
</details>

**Comment by ghostwords** [comment]
>In German

Ah, it seems that German strings aren't much longer than English strings in this case. For instance, button text fits on the same line instead of wrapping.

**Comment by andresbase** [comment]
Tried with Spanish, French, and Portuguese and none run on a second line on 360px.

**Comment by ghostwords** [comment]
One of the error report wraps in Russian, while the other doesn't:

Screenshot from 2020-07-08 11-34-54

The buttons had different heights prior to the fix in eafab16bf954f6fa6daaf12ec8621f8be0139df7.

**Pull request merged**
