### PR TITLE
Add replacement placeholder for Quora

### LINKED ISSUE #2824: Breaks Quora embeds
#### Browser:
Google Chrome
#### Brower version: 
96.0.4664.110 (Official Build) (64-bit)

A quora post (https://medium.com/@shreshthsharma689/why-dont-we-hit-the-sun-5ab8bb2a94e5) shared on www.medium.com is getting broken and when the culprit domain (www.quora.com) is set to yellow, the issue gets fixed.

#### Culprit Domain : 
`www.quora.com`

#### Debug output:

```
**** ACTION_MAP for quora.com
a.quora.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1640281958505,
  "userAction": ""
}
log.quora.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1640535989962,
  "userAction": ""
}
q.quora.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1640078801134,
  "userAction": ""
}
quora.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
www.quora.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1640474712318,
  "userAction": "user_block"
}
**** SNITCH_MAP for quora.com
quora.com [
  "talentlms.com",
  "fool.com",
  "fatherly.com"
]
```

### PR DESCRIPTION
**Pull request by clasick**
Fixes #2824.

Preview:

### CODE REVIEW

**Comment by ghostwords** [comment]
Thank you for the pull request!

Do you have examples of other sites using the Quora widget? I haven't seen any in Privacy Badger user error reports. I would rather not add a widget for something that isn't widely used.

**Comment by clasick** [comment]
@ghostwords Not sure, I just added it based on #2824. So we know Medium definitely has one, maybe the issue creator @shreshth3142857 might know about more.

**Comment by clasick** [comment]
@ghostwords Not sure, I just added it based on #2824. So we know Medium definitely has one, maybe the issue creator @shreshth3142857 might know about more.

**Comment by ghostwords** [comment]
OK, let's hold off on adding a Quora widget placeholder for now.

**Comment by shreshth3142857** [comment]
> @ghostwords Not sure, I just added it based on #2824. So we know Medium definitely has one, maybe the issue creator @shreshth3142857 might know about more.

hey , at that time there was issue with the placeholder , I was an avid quora user, if you havent received much reports about this issue, then its fine, :)

**Comment by ghostwords** [comment]
>how come this issue come again?

Just periodically pruning issues/PRs.

**Pull request closed without merging**
