### PR TITLE
Add Bilibili domains to MDFP list

### PR DESCRIPTION
**Pull request by Gowee**
> Bilibili is a video sharing website themed around animation, comic, and game based in China, where users can submit, view, and add commentary subtitles on videos. [Wikipedia](https://en.wikipedia.org/wiki/Bilibili)

Bilibili have several different domains using resources hosted on hdslb.com which is blocked by the Badger. AFAICS, only unblocking hdslb.com makes both bilibili.com and biligame.com work as expected. But to avoid future troubles, I suppose it may be more desirable to add all of known domains to the MDFP list.

The Sub Alt Name section of the TLS certificate of Bilibili.com does not give a full list of Bilibili's domains, so the domains in this commit are collected from its web pages and results of search engines. 

Debugging logs:
```
**** ACTION_MAP for hdslb.com
static.hdslb.com {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": TIMESTAMP_REDACTED
}
hdslb.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
s1.hdslb.com {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": TIMESTAMP_REDACTED
}
i2.hdslb.com {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": TIMESTAMP_REDACTED
}
i1.hdslb.com {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": TIMESTAMP_REDACTED
}
i3.hdslb.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": TIMESTAMP_REDACTED
}
i0.hdslb.com {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": TIMESTAMP_REDACTED
}
activity.hdslb.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": TIMESTAMP_REDACTED
}
s2.hdslb.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": TIMESTAMP_REDACTED
}
backup.hdslb.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": TIMESTAMP_REDACTED
}
**** SNITCH_MAP for hdslb.com
hdslb.com [
  "bilibili.com",
  "biligame.com",
  ""
]
```

### CODE REVIEW

**Comment by ghostwords** [comment]
This is great, thank you so much!

Hmm, I wonder if there is an easy way to query all public SSL certificates, say by Organization. CertDB? Seems [helpful but incomplete](https://certdb.com/search/index?q=organization%3A%22%E4%B8%8A%E6%B5%B7%E5%B9%BB%E7%94%B5%E4%BF%A1%E6%81%AF%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8%22).

**Comment by ghostwords** [comment]
>But to avoid future troubles, I suppose it may be more desirable to add all of known domains to the MDFP list.

That's cool, but I wouldn't go out of my way for completeness' sake. Our MDFP lists aren't meant to be comprehensive.

**Comment by ghostwords** [comment]
The `""` in snitch map (the list of first-party site base domains where the tracking was seen) is a bug. Which browser do you use? Any ideas as to how reproduce this entry (with a new browser profile)?

**Comment by Gowee** [comment]
> Hmm, I wonder if there is an easy way to query all public SSL certificates, say by Organization.

There is an effort & standard to log all public TLS certificates for PKI/CA security called Certificate Transparency. Several websites provides with free search service (e.g. https://www.entrust.com/ct-search/ , https://crt.sh/). But it have several limitations. One of the main problem is that only certificates issued under Organization Verification (while most are under Domain Verification) have organizations/companies embedded in certificates. So it is not feasible to query "by Organization" under most circumstance with CT.

I not sure but CertDB seems to be powered (partially?) by human and it won't be complete (especially for domains of relatively small companies).

The other way I attempted several times is to ask Google for all domains hosted on their authoritative DNS server (e.g. dig google.com NS). But it often does not work due to either the lack of knowledge from Google or the lack of independence of DNS server (they may use public DNS server such as AWS Route 53). 

I would like to suggest to let the Badger collect interrelated domains data (privacy concerning may be taken into consideration) so that to check it for the sake of completeness if necessary when updating MDFP.


> The "" in snitch map (the list of first-party site base...

Firefox Quantum 68.0.2 (64-bit) on Windows 10. Sorry but no idea. I might try to set up a new profile for testing tomorrow.

**Comment by Gowee** [comment]
https://ssltools.digicert.com/checker/views/ctsearch.jsp looks good to me when searching for "上海幻电信息科技有限公司".

**Pull request merged**
