### PR TITLE
Make the Facebook share widget replacement button say 'share' not 'like'.

### PR DESCRIPTION
**Pull request by cowlicks**

### CODE REVIEW

**Comment by cowlicks** [comment]
Before:
https://github.com/EFForg/privacybadger/blob/master/src/skin/socialwidgets/FacebookShare.svg
After: https://github.com/cowlicks/privacybadgerchrome/blob/b2a3fae5ff2927c81c67e2571cad04d170a79f9f/src/skin/socialwidgets/FacebookShare.svg

@SwartzCr I don't understand why this was marked as "in progress", it is ready for review.

**Comment by ghostwords** [comment]
It's a bot I'm pretty sure, set up by @andresbase maybe?

**Comment by ghostwords** [comment]
Speaking of reviewing, @cowlicks, let's use GitHub's reviewing functionality. Assign it to me for review when it's ready, and I'll get notified. When you are reviewing and your review is done, mark the issue approved, or mark it as needing changes using the review submission form.

**Comment by ghostwords** [comment]
A couple of Facebook examples here: https://github.com/EFForg/privacybadger/pull/1432#issuecomment-310804633. Do we have any more at this point?

**Comment by cowlicks** [comment]
Examples found [here](https://publicwww.com/websites/%22share_button.php%22/):

http://www.examresults.net/ 
http://pokekueez.com/
https://www.meta-chart.com/

I think we don't catch some "like" and "share" buttons, because they are newer versions that don't match the querySelector we use to find these. But that is a separate issue.

The alignment of the text changes based on your fonts and other svg stuff that I don't understand (The tweet have always been misaligned on my computer). These edits maintain fontsize and styling and just change the text and fit the box to it. There may be a way to get it consistently aligned across devices, but I don't think it is worth the effort now. It should be a separate issue.

I'm not sure what you mean by "keep working on it". Do you want to merge this? The cases where this helps is any time this button is loaded, it used to say "Like" even though it was a "Share" button, and we already have a "Like" button.

**Comment by ghostwords** [comment]
Also https://sharemenot.cs.washington.edu/Test%20Installation.shtml.

**Pull request merged**
