### PR TITLE
Improve popup on special pages

### LINKED ISSUE #1311: Manual slider changes are not saved in the configuration window
Using FireFox 52.0.2 on macOS Sierra 10.12.4
Sometimes when manually changing a slider in the configuration window, by clicking on the slider bar, the position/color of the slider effectively change (e.g. from right/green to middle/yellow to left/red), but then when scrolling down the position is set back to right (but the color remains red) and the tooltip for the server still says "blocked". Upon reloading the configuration window, however, the slider has moved back to its original left/green state.

### LINKED ISSUE #1492: Make popup.js revertDomainControl return slider to best position
revert-dom-control

### LINKED ISSUE #1625: Don't show tracker message in popup on extension pages.
I watched a user install privacy badger, they clicked on the icon on the first run page and read message. The text is incorrect and irrelevant on pages like this. It confused them. The text says:
>Privacy Badger detected potential trackers on this page. These sliders let you control how Privacy Badger handles each one. You shouldn't need to adjust them unless something is broken.

pb-dont-show-on-nonpages

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #1625.

Fixes #1311, fixes #1492 by virtue of reloading the popup after clicking the undo arrow (as well as the enable/disable Badger buttons). This doesn't need to be in this PR; if it causes trouble, let's break it out.

Related to #1627.

Does not fix:
- Poor button placement on whitelisted sites
- Unneeded scrollbars in Firefox (#1610)
- Not recognizing `chrome://extensions` (or Chrome Web Store, or `about:debugging` in Firefox, ...) as a special browser page
- Popup showing the tutorial message when opened on the tutorial page following a new install
- Browser button not getting updated to reflect site whitelist updates in tabs outside of the active tab when enabling/disabling Badger on a site open in multiple tabs

Before:
screenshot from 2017-10-18 11 21 26

After:
screenshot from 2017-10-19 10 12 13

### CODE REVIEW

**Comment by ghostwords** [comment]
@lemnis @andresbase I have not tested on Android, I hope this doesn't break anything.

**Comment by ghostwords** [comment]
Need to fix (or disable, maybe until #1634) popup tests. The problem is that the popup is opened in a situation that looks like a special browser page, so that site whitelisting and error reporting buttons as well as the trackers link are now missing. They should be, but the tests still look for them.

**Comment by ghostwords** [comment]
Tests were also failing since the enable/disable buttons test is no longer applicable as we close the popup instead. I removed it for now (b6b1912ec8ae771d163c7e641a94b1f740d98732).

Pulled in 232c3c0ca9c4eb582f21b7a2b401f0fecbe7ed5a from #1430 to assist with getting the remaining popup tests passing again.

**Comment by ghostwords** [comment]
@andresbase Sorry, I added a few potentially breaking changes while fixing tests; we should retest.

**Comment by andresbase** [comment]
Tests in macOS, Windows 10, Linux with Chrome and FF Latest versions:
* [x] Don't show tracker in options 
* [x] Sliders when reloading to correct position
* [x] Undo arrow reloads page and closes popup

* [ ] Android (xpi not loading, will try again)
* [ ] Linux FF 56.0 (Some weirdness, need to investigate if it's my install or something else)

**Comment by andresbase** [comment]
I was also thinking that the text "There are no third party resources on this site." could be larger or bold so it stands out from all the other text above it that says the usual "Privacy Badger detected 0..."

For the largo logo after inquiring with other people it seems it looks ok while we redesign the UI.

**Comment by andresbase** [comment]
The tooltip is empty for firefox
tooltip


```
Tooltipster: one or more tooltips are already attached to the element below. Ignoring.  tooltipster.bundle.min.js:1:28554
<a id="options" href="/skin/options.html" class="control-button grey-button tooltip tooltipstered" style="display:block" target="_blank">  tooltipster.bundle.min.js:1:28656
Tooltipster: one or more tooltips are already attached to the element below. Ignoring.  tooltipster.bundle.min.js:1:28554
<a id="help" href="/skin/firstRun.html" class="control-button grey-button tooltip tooltipstered" style="display:block" target="_blank">  tooltipster.bundle.min.js:1:28656
```

**Comment by ghostwords** [comment]
What are the steps to reproduce?

**Comment by andresbase** [comment]
I just installed PB in Firefox 56 and hover over the border when you click on the PB icon.

**Comment by ghostwords** [comment]
I can't reproduce. Could it be that you installed Badger from a branch that doesn't have the new translation strings used in your screenshot, and then switched branches but didn't reload Badger in the browser? Translations are loaded on Badger startup only. A few files (popup.html, popup.js) don't seem to require reloading to see new versions of, but most everything else does.

**Comment by andresbase** [comment]
Indeed, that must have been the problem, thanks! I can't reproduce the performance issues anywhere else either. They are persistent in my work machine but nowhere else.

**Pull request merged**
