### PR TITLE
Add OVH domains to MDFP list

### LINKED ISSUE #636: kimsufi.com payment page depends on ovh.com resources
I think you can reproduce this publicly without logging in (and without actually paying, of course):
- Visit https://us.kimsufi.com/cgi-bin/order/renew.cgi
- Enter `ns504970.ip-198-27-64.net` (my server)
- Select some renewal period
- Look for the icons under "Payment by card"

Privacy Badger, for me, has a red slider for www.ovh.com, but it seems at least images from that site need to be loaded so I can click on the links. Kimsufi is a brand of OVH (same organization), so there's no loss to privacy in allowing cross-origin requests between kimsufi.com and ovh.com.

I'd imagine the same thing is true of soyoustart.com, which is also an OVH brand. They also have a payment page at the corresponding URL.

### LINKED ISSUE #2096: ovh-hosting.fi is broken, it depends of ovh.com resources
ovh-hosting.fi, ovh.ie, ovh.us, ovh.de etc. are OVH's country-specific sites and if they can't get resources from ovh.com, ordering pages are broken.

So they should be added to the MDFP list.

Related to https://github.com/EFForg/privacybadger/issues/636.

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #2096, fixes #636.

### CODE REVIEW

**Comment by bcyphers** [comment]
What about https://www.ovhtelecom.fr/?

**Comment by ghostwords** [comment]
Yep, looks like it's part of OVH. Unfortunately OVH doesn't make use of the Subject Alternative Name field in their certificates ...

**Comment by ghostwords** [comment]
Added `ovhtelecom.fr`.

**Comment by bcyphers** [comment]
There may be more, but I couldn't find them in a quick search. Merging now.

**Pull request merged**
