### PR TITLE
Yellowlist Kayak's CDN domain

### PR DESCRIPTION
**Pull request by pde**
This domain seems Kayak-specific, but I found Kayak results pages were broken until I manually yellowlisted it.

### CODE REVIEW

**Comment by pde** [comment]
Perhaps worth noting that the actual hostname they use is `a1.r9cdn.net`.

**Comment by ghostwords** [comment]
Might be a better fit for [multiDomainFirstParties.js](https://github.com/EFForg/privacybadger/blob/02d5d9d64f45b2b8bae72f621b4404ff607ee211/src/multiDomainFirstParties.js) (#781).

**Comment by pde** [comment]
Maybe. But I thought we only needed to use that when a CDN domain needs a cookie? Or are we trying to use it as our first line of defense?

**Comment by ghostwords** [comment]
Could you share your snitch map for `r9cdn.net`? Run the following in Badger's background page console: `badger.storage.snitch_map.getItem("a1.r9cdn.net")`. This will tell us where PB saw this domain perform suspected tracking.

If this is an exclusively Kayak-related domain, it seems to me that we should mark it as such, resolving the issue. Which of our fallback mechanisms is most appropriate, which one resolves the breakage while increasing privacy exposure by the smallest amount? I see yellowlisting as more of a last resort.

**Comment by ghostwords** [comment]
Also, I'm getting more and more keen on implementing #963.

**Comment by pde** [comment]
```
badger.storage.snitch_map.getItem("r9cdn.net")
["kayak.com", "kayak.com.au", "kayak.co.uk"]
```

**Comment by cowlicks** [comment]
@ghostwords when I wrote #1214 I didn't realize there had been discussion about this! I'm very interested in implementing this too. I think the data we would gather would allow us to be a lot smarter about what we block. And we would eventually save a lot of developer time which would otherwise be spent fixing site bugs and maintaining the cookieblock list.

**Comment by ghostwords** [comment]
Also, looks like regular and "legacy" cookieblock lists have drifted apart again:
```diff
@@ -81,12 +81,12 @@ cloudflare.com
 cloudfront.net
 bbc.co.uk
 bbci.co.uk
+gr-assets.com
 grapeshot.co.uk
 w.graphiq.com
 s.graphiq.com
 s2.graphiq.com
 s3.graphiq.com
-gr-assets.com
 guardian.co.uk
 media-imdb.com
 mediaworks.co.nz
@@ -372,7 +372,7 @@ onswipe.com
 api.ooyala.com
 c.ooyala.com
 l.ooyala.com
-opf.ooyala.com
+opf.ooyala.com^third-party
 player.ooyala.com
 tile.opencyclemap.org
 tile2.opencyclemap.org
@@ -410,12 +410,8 @@ psswrdbx.com
 publiekeomroep.nl
 qualtrics.com
 quotemedia.com
-api.razorpay.com
-checkout.razorpay.com
-razorpay.com
 rackcdn.com
 rackspacecloud.com
-r9cdn.com
 rambler.ru
 images.rapgenius.com
 readability.com
```
Previously: https://github.com/EFForg/privacybadger/pull/968#issuecomment-255117640. We fixed this with ac97f9c819f3313d78fc5f299a65e86fcb8e0e5d, but I'm not sure now when the fix script gets run and whether the fixes ever get committed back to the repo. Basically confused whether whether we should be updating both lists by hand or not (looks like other people are too, note the messed-up entry for `opf.ooyala.com`).

**Comment by ghostwords** [comment]
Oops, never mind, this branch is 5 mos old, the lists in master match.

**Comment by ghostwords** [comment]
Closing in favor of #1253.

**Pull request closed without merging**
