### PR TITLE
Fix export data

### LINKED ISSUE #1318: Can't export user data when data grows beyond a certain size
When clicking the download button, Chrome keeps saying Failed - Network error. I tried on a separate profile, and it works. I tried disabling all other extensions on my main profile and it still gives the error. Is there anything I can type into the console to figure out what is causing the issue?

image

### PR DESCRIPTION
**Pull request by lemnis**
Should fix #1318

### CODE REVIEW

**Comment by ghostwords** [comment]
To test adding additional permissions in Chrome, see [Testing permission warnings](https://developer.chrome.com/extensions/permission_warnings#test) in Chrome Extensions developer documentation. You can package our extension by running `make` in the extension's root folder. Here is an example update manifest I used:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
  <app appid='GET-THIS-ID-FROM-THE-CHROME-EXTENSIONS-PAGE-AFTER-DRAGGING-AND-DROPPING-THE-CRX'>
    <updatecheck codebase='http://localhost:9999/privacy_badger-2017.7.25.crx' version='2017.7.25' />
  </app>
</gupdate>
```

**Comment by lemnis** [comment]
The previous method also supports blobs and fixes the bug within chrome, but will not work in Firefox ([bugzilla bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1379954)).

While I don't know the previous discussion around changing this specific code, I think adding this permission and as result, an automatic disabling of the extension will benefit the user in the long run.

**Comment by ghostwords** [comment]
I don't think we should make users go through the disable-and-reenable process, which will result in losing a significant percentage of our userbase, unless we absolutely have to. This bug isn't high profile enough to warrant this step; there may yet be another workaround; PR #1462 should make the issue disappear for most people.

**Comment by ghostwords** [comment]
>The previous method also supports blobs and fixes the bug within chrome, but will not work in Firefox

I am not sure what you mean by this, could you elaborate please?

**Comment by lemnis** [comment]
Look at the latest commit, easier than me explaining it

**Comment by lemnis** [comment]
The code must switch to a blob, otherwise, the bug will be keep creeping up. How chrome is coded, an url can only be a certain length, a blob will fix this.

**Comment by ghostwords** [comment]
OK, I see, you linked to a Bugzilla issue above that itself is marked as a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1331176. It seems like downloading blobs doesn't work in Firefox 52, but might have been fixed some time since then.

**Comment by ghostwords** [comment]
Merged in cde3fd8f62c2de1044fc9e73a0f179962f93a9d7. Thanks again!

**Pull request closed without merging**
