### PR TITLE
Improve wording around list of sites Badger is disabled on

### LINKED ISSUE #2045: Reduce confusion around Whitelisted Domains
It seems that users sometimes mistake Whitelisted Domains for the place they need to enter domains they want Privacy Badger to allow to load. It may be that removing explanation of sliders from the new user intro page as well as moving the Tracking Domains tab out of the way (it used to be the default tab) contributes to this confusion.

We should be able to help by amending the description over the whitelisted domains form. I don't think it's clear the form is about turning Privacy Badger off entirely on sites you visit, not about allowing third-party domains to load. 

For example, see #2044, also this recent AMO review:
>Хорошее расширение, но почему-то не работает белый список. Вводишь в белый список домен radikal.ru, а изображения на других сайтах всё равно блокируются.

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #2045. Updated tab name, form description.

screenshot from 2018-07-01 16 37 29

### CODE REVIEW

**Comment by andresbase** [comment]
How about something like:

> Privacy Badger is disabled on the following sites. This means that Privacy Badger will not block anything when you visit the sites listed here. 
If you think Privacy Badger is breaking a page, you can type that page's domain in the box below and click the \"Add domain\" button. 
Alternatively, when you already have the page's tab selected, you can also just click on Privacy Badger's button in the browser toolbar and then click the \"Disable\" button

**Comment by ghostwords** [comment]
Updated:
screenshot from 2018-07-05 16 57 40

**Comment by ghostwords** [comment]
Nice! Thanks, sending to translators.

**Comment by ghostwords** [comment]
Followup commit: 2b9f1f21cf9c7d9cbfd95b35733ffc167247c7e7

**Pull request merged**
