### PR TITLE
Translate new messages about trackers and social buttons

### PR DESCRIPTION
**Pull request by Bisaloo**
I would like to test this locally before you merge it.

@ghostwords, how can I change the language of the extension? Currently, it uses my OS locale, which is English.

### CODE REVIEW

**Comment by ghostwords** [comment]
A quick/hacky way to change the locale is to temporarily copy the locale you want to use to your default locale's folder in `src/_locales/` and reload Privacy Badger.

The proper way would be to launch the browser in your desired locale.

For Chrome, it might be as easy as [launching it from the command line with `LOCALE=fr` (for example) in front of the executable](https://stackoverflow.com/questions/24992240/start-google-chrome-with-a-specific-locale-using-a-command-line-argument).

[Firefox seems to require more effort](https://askubuntu.com/questions/63724/how-do-i-start-firefox-in-another-language-than-the-default).

**Comment by Bisaloo** [comment]
@ghostwords, I still see messages like "Privacy Badger detected 0 potential trackers..." (translated) after installing the version from my branch. Am I doing something wrong?

**Comment by Bisaloo** [comment]
This happens when I visit website with third parties that haven't been detected as tracking by PB.

rect3358

**Comment by ghostwords** [comment]
Do you mean you expect to see the "hooray for privacy!" message instead? That message is shown on sites with no third-party resources at all, for example `eff.org`.

**Comment by Bisaloo** [comment]
> Do you mean you expect to see the "hooray for privacy!" message instead? That message is shown on sites with no third-party resources at all, for example https://www.eff.org/.

Oh okay, so this is expected.

**Comment by Bisaloo** [comment]
Tested locally and everything looks fine. Ready for review.

**Comment by ghostwords** [comment]
I pulled in the latest translations from Transifex a few minutes ago and realized that a contributor on Transifex also translated the latest changes into French. I'm sorry about the duplication of effort!

Would you mind taking a look at [their translations](https://github.com/EFForg/privacybadger/commit/e4a87a55409f4c430c876e2131f2a07f76426bbb#diff-d83aaaae81efc1135fd306b6fcc5fc79) and updating your PR if anything needs fixing?

**Comment by Bisaloo** [comment]
> I'm sorry about the duplication of effort!

It's okay, don't worry.

> Would you mind taking a look at their translations and updating your PR if anything needs fixing?

I don't see anything wrong. Closing this.

**Pull request closed without merging**
