### PR TITLE
Add shopifycdn.com to yellowlist

### LINKED ISSUE #1499: productreviews.shopifycdn.com
https://impressionsvanity.com/collections/hollywood-vanity-mirrors/products/hollywood-glamour-vanity-mirror?variant=34770708547

`productreviews.shopifycdn.com` breaks reviews at bottom.

image

### PR DESCRIPTION
**Pull request by terrorist96**
fixes #1499

### CODE REVIEW

**Comment by ghostwords** [comment]
Could you move the changes from #1586 here? I would add another commit here and close the other PR.

**Comment by terrorist96** [comment]
Don't know how to do that. I'm using the web interface; I don't have git installed on my computer.

**Comment by ghostwords** [comment]
Oh OK, no problem. @cowlicks or I will review this later and merge both then. The harm is cluttering up the issue tracker with redundant PRs and email notifications. I'd rather avoid it, but no big deal.

**Comment by ghostwords** [comment]
Also, I guess you don't technically need to update the legacy list at all. I can do that myself at the time of releasing the updates.

**Comment by ghostwords** [comment]
Sorry, I prematurely labeled the parent issue as "yellowlist", but I can't reproduce the tracking. I think the fix is to make a migration to clean up whatever domains we can't reproduce. I relabeled #1499 as such.

**Pull request closed without merging**
