### PR TITLE
Add hive01 GmbH / openDesktop.org domains to MDFP list

### PR DESCRIPTION
**Pull request by Gowee**
Broken (or partially broken) pages:
- https://www.gnome-look.org/ (-> `{cdn, www}.pling.com`)
- https://www.opencode.net/explore (-> `www.opendesktop.org`, `www.pling.com`)
- ...

The domains list are collected from:
- https://github.com/duckduckgo/tracker-radar/blob/main/entities/hive01%20gmbh.json#L11
- https://www.opencode.net/alisacarolina/ocs-store/blob/master/app/scripts/renderers/ipc-renderer.js (appears in my search result)
- https://tools.ipip.net/ipdomain.php (lookups domains resolved to a given IP address)

Debugging output for `opendesktop.org`:
```
**** ACTION_MAP for opendesktop.org
opendesktop.org {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
www.opendesktop.org {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime":  /* REDACTED */
}
piwik.opendesktop.org {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime":  /* REDACTED */
}
cn.opendesktop.org {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime":  /* REDACTED */
}
**** SNITCH_MAP for opendesktop.org
opendesktop.org [
  "gnome-look.org",
  "pling.com",
  "xfce-look.org"
]
```

Debugging output for `pling.com`:
```
**** ACTION_MAP for pling.com 
pling.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
} 
www.pling.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime":  /* REDACTED */
} 
/* ... */
cdn.pling.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime":  /* REDACTED */
} 
**** SNITCH_MAP for pling.com 
pling.com [
  "gnome-look.org",
  "opendesktop.org",
  "kde.org"
]
```

DNS resolution result:
```
139.59.206.243  STREAM opendesktop.org
46.101.238.240  STREAM vlc-addons.org
46.101.238.240  STREAM appcentral.org
46.101.238.240  STREAM appimagehub.com
46.101.238.240  STREAM apps.plasma-bigscreen.org
46.101.238.240  STREAM box-look.org
46.101.238.240  STREAM cccliparts.org
185.246.45.82   STREAM compiz-themes.org
46.101.238.240  STREAM share.krita.org
46.101.238.240  STREAM electron-apps.com
46.101.238.240  STREAM enlightenment-themes.org
46.101.238.240  STREAM free-artwork.org
46.101.238.240  STREAM gnome-look.org
46.101.238.240  STREAM historical-look.org
46.101.238.240  STREAM kde-apps.org
46.101.238.240  STREAM kde-look.org
46.101.238.240  STREAM linux-apps.com
46.101.238.240  STREAM linux-games.org
46.101.238.240  STREAM mate-look.org
46.101.238.240  STREAM mycroft-skills.org
46.101.219.181  STREAM opencode.net
46.101.238.240  STREAM pling.com
46.101.238.240  STREAM share.krita.org
46.101.238.240  STREAM store.falkon.org

# store.kde.org
104.26.10.56    STREAM store.kde.org.cdn.cloudflare.net
104.26.11.56    STREAM 
172.67.73.202   STREAM 

46.101.238.240  STREAM trinity-look.org
46.101.238.240  STREAM vlc-addons.org
46.101.238.240  STREAM xfce-look.org
```
Among these domains:
- `compiz-themes.org` is not included as not currently pointed to `46.101.238.240` and it shows `503 Service Unavailable`.
- `opendesktop.org` and `kde.store.org` are clearly related to the remaining majority according to their page layout/content.
- `opencode.net` and `opendesktop.org` are related as they are referring to each other in the top bar on their pages.

### CODE REVIEW

**Comment by Gowee** [comment]
CI error:
```
E       AssertionError: False is not true : The following QUnit tests failed:

E         * MDFP domains are all base domains

E         * MDFP domains do not contain duplicates
```

**Comment by Gowee** [comment]
Still:
```
* MDFP domains are all base domains
```

`share.krita.org`, `addons.videolan.org`, `store.falkon.org` and `store.kde.org` are using assets on `pling.com` and `opendesktop.org`. What is the proper way to handle this case?

**Comment by ghostwords** [comment]
We currently need MDFP entries to all be "base" (eTLD+1) domains because that's what MDFP entries get compared to. So if we put in a subdomain (eTLD+2 or greater), it would never match any site domains. Does this help?

**Comment by Gowee** [comment]
I do understand. Thanks for the explanation. 

But I am not sure how to handle this corner case where eTLD+2 subdomains are delegated to third-party entities. Putting `pling.com` and `opendesktop.org` into the yellowlist or just discarding these non-base domains for now? Do you have any advice?

**Comment by ghostwords** [comment]
Yes, I think so, we should yellowlist `pling.com` and `opendesktop.org`. I'll do this now. Thank you!

**Pull request closed without merging**
