### PR TITLE
Adds Recurly to yellowlist

### PR DESCRIPTION
**Pull request by chrissrogers**
- Recurly provides payment processing on behalf of merchants. Requests contain PII for the purpose of tokenizing payment information prior to committing a transaction on behalf of a merchant
- recurly/recurly-js#468

### CODE REVIEW

**Comment by ghostwords** [comment]
Hello! Would Recurly be able and willing to abide by the [EFF Do Not Track policy](https://www.eff.org/dnt-policy)'s requirements on `recurly.com`? If yes, posting the DNT policy on the domain will automatically tell Privacy Badger to always allow loading of resources from that domain.

**Comment by chrissrogers** [comment]
DNT compliance is something we're currently reviewing. We're committed to complying on as many domains as we're able, but must first confer with auditors to ensure we don't run afoul of regulations. 

We have a preliminary set of steps to push us toward compliance, but which are only not feasible in the short term. In the meantime, we'd like to request yellowlisting to ensure our customers are able to utilize our service while we strive meaningfully toward compliance.

**Comment by ghostwords** [comment]
Sounds good!

Have you confirmed that setting `recurly.com` to "yellow" restores broken functionality?

**Comment by chrissrogers** [comment]
I've confirmed that yellowlisting the specific domains js.recurly.com and api.recurly.com results in full functionality. My read on the yelloowlist is that `recurly.com` will cover both of these domains -- is that correct?

**Comment by ghostwords** [comment]
>My read on the yelloowlist is that recurly.com will cover both of these domains -- is that correct?

Correct.

**Comment by ghostwords** [comment]
Will merge and release the updated yellowlist tomorrow morning.

**Comment by chrissrogers** [comment]
Beautiful! Thank you kindly.

**Comment by ghostwords** [comment]
The updated yellowlist is now live. You should see this update get applied to your Badger within the next day. You can also get it right away by restarting your browser.

Let me know if you have any questions regarding DNT adoption.

**Comment by ghostwords** [comment]
Thank you for the PR!

**Pull request merged**
