### PR TITLE
Unwrap t.co links on tweetdeck

### LINKED ISSUE #1651: Support t.co unwrapping on TweetDeck
Following up on #1392. TweetDeck requires a slightly different query (b348e037dbd989e368640658ce8d74a5ff255ee0).

### PR DESCRIPTION
**Pull request by cowlicks**
closes #1651 

This gets most links except for image links, they can be done in a seperate PR. Those links look like:
```javascript
<a class="js-media-image-link block med-link media-item media-size-medium   is-zoomable" href="https://t.co/JFf6tr0uAx" rel="mediaPreview" target="_blank" style="background-image:url(https://pbs.twimg.com/media/DJEQ01jVAAAQsqQ.jpg)" data-media-entity-id="905523499992678400">      </a>
```

### CODE REVIEW

**Comment by ghostwords** [comment]
What are "image links"? How common are they on TweetDeck?

**Comment by cowlicks** [comment]
They look like links to images. To see the misses run `document.querySelectorAll("a[href^='https://t.co']");`

With this PR, loading tweetdeck I see:
```javascript
(10) [a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable]
```
Without this pr I see:
```javascript
(35) [a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable, a.url-ext, a.url-ext, a.url-ext, a.url-ext, a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable, a.url-ext, a.js-media-image-link.pin-all.media-image.block, a.js-media-image-link.pin-all.media-image.block, a.js-media-image-link.pin-all.media-image.block, a.js-media-image-link.pin-all.media-image.block, a.url-ext, a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable, a.url-ext, a.url-ext, a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable, a.url-ext, a.url-ext, a.url-ext, a.url-ext, a.url-ext, a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable, a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable]length: 350: a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable1: a.url-ext2: a.url-ext3: a.url-ext4: a.url-ext5: a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable6: a.url-ext7: a.js-media-image-link.pin-all.media-image.block8: a.js-media-image-link.pin-all.media-image.block9: a.js-media-image-link.pin-all.media-image.block10: a.js-media-image-link.pin-all.media-image.block11: a.url-ext12: a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable13: a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable14: a.url-ext15: a.url-ext16: a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable17: a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable18: a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable19: a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable20: a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable21: a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable22: a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable23: a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable24: a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable25: a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable26: a.js-media-image-link.block.med-link.media-item.media-size-small.is-zoomable27: a.url-ext28: a.url-ext29: a.url-ext30: a.url-ext31: a.url-ext32: a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable33: a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable34: a.js-media-image-link.block.med-link.media-item.media-size-medium.is-zoomable__proto__: NodeList
```

**Comment by ghostwords** [comment]
Could you post a screenshot of an image link?

**Comment by bcyphers** [comment]
We should take another look at this after #2016 gets merged in.

**Pull request closed without merging**
