### PR TITLE
add: way to avoid being nagged on first run

### PR DESCRIPTION
**Pull request by serv-inc**
As discussed in https://github.com/EFForg/privacybadger/pull/2211.

This is a very simple change, just the minimal settings for it to work. To test, you also need a configuration, say the file `/etc/chromium-browser/policies/managed/eff.json` on Linux, with the content:

```json
{
    "3rdparty": {
	"extensions": {
	    "pkehgijcmpdhfbdbbnkijodmdjhbjlgp": {
		"nagMeNot" : true
	    }
	}
    }
}
```
(if you test with a temporarily loaded extension in Chrome, you need to change this `pke...` id to the temporary extension's id)

I was not sure where to store this value inside `BadgerPen`. Should it be inside `settings_map`? Or as a separate `KEY`? If you have some design on how to integrate, and would like help, feel welcome.

PS: last pull request changed the wrong file, would not have worked

### CODE REVIEW

**Comment by ghostwords** [comment]
Thank you for the PR! I'll take a proper look on Monday probably. For now, you could fix/rebase to fix the lint complaints. Also:
- Storing the new value inside `settings_map` sounds good. (We already store internal/not exposed in the UI settings there.)
- Could I ask you to test this in Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1386427) too?
- Are there existing docs for how to use this feature in Chrome and Firefox we could link to, or should we write up the steps to do so ourselves?

**Comment by serv-inc** [comment]
>  For now, you could fix/rebase to fix the lint complaints
done

**Comment by serv-inc** [comment]
> Could I ask you to test this in Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1386427) too?
 
done. The file in `src/doc/jid1-MnnxcxisBPnSXQ@jetpack.json` contains an example file that can be put to `~/.mozilla/managed-storage`. See also https://superuser.com/questions/1303910/translate-google-chromes-storage-from-policies-managed-json-to-firefox.

**Comment by serv-inc** [comment]
> This is great, thank you!

You're welcome. Thank you for your guidance.

> I'll add support for disabled sites and update Privacy Badger docs next.

Awesome.

**Comment by ghostwords** [comment]
OK, code updates should be done for now. I added support for more flags as well as the disabled sites list. Please note I renamed the "show intro page" flag (to something more boring but hopefully clear). Still need to document how to use admin policy settings.

**Comment by ghostwords** [comment]
@serv-inc Documentation added. Let me know what you think of it and the rest of the above changes please.

**Comment by serv-inc** [comment]
> Let me know what you think of it and the rest of the above changes please.

At first glance, this looks awesome. Docs seem clear (to me), code seems clean. Did you add tests to see the effect of, say `disabledSites`?

**Comment by ghostwords** [comment]
To test this we'd (I think) need to update `pbtest.py` to set up the managed policy for the browser (inside `firefox_manager`/`chrome_manager`?) when running the managed policy test. We'd need to check the platform we run on (maybe only run the test on Linux ...) and then do the appropriate thing (copy the test policy to the right folder). I'm not happy about modifying the local filesystem for this test though. I guess I'm OK not adding the test for now. Do open a PR if you find a better way to do this (if only in one browser; a Firefox test is better than no test).

**Pull request merged**
