### PR TITLE
Update Twitter Social Widget file to the new Icon

### PR DESCRIPTION
**Pull request by retiform**
I would like to note that the twitter logo uses a rastorized source for the twitter part, but it is high enough resolution that no one should notice unless they zoom in a lot on a very hi res screen.  Partial Fix to  #1857

### CODE REVIEW

**Comment by ghostwords** [comment]
>Really the icons should probably just be generated like they are by twitter, with css

What do you mean? We do have the ability to [specify styles on the replacement button](https://github.com/EFForg/privacybadger/blob/d27019fad2afb6a45fd25a09caf4c23223fb1c54/src/js/contentscripts/socialwidgets.js#L120-L123). But why does the Twitter button we have now have appropriate sizing? Can we specify the desired dimensions inside the SVG document?

**Comment by retiform** [comment]
> What do you mean? We do have the ability to specify styles on the replacement button.   

The actual twitter button is a combination of text, an svg (for the bird logo)
and a button, all specified by a css stylesheet. It is not just one static SVG file.

**Comment by ghostwords** [comment]
Did you mean to say the bird image right now is a raster image but should be a vector shape like in Twitter's own button? Sure, let's do that.

But like I asked before, our current Twitter replacement button also uses a raster image for the bird, but is scaled appropriately. Can't we just specify the dimensions we want in SVG properties like we do now too?

**Comment by retiform** [comment]
> Did you mean to say the bird image right now is a raster image but should be a vector shape like in Twitter's own button? Sure, let's do that.

No I meant to say the little blue box around the bird is just CSS, there is no SVG. The word "tweet" is also just html + css

> But like I asked before, our current Twitter replacement button also uses a raster image for the bird, but is scaled appropriately. Can't we just specify the dimensions we want in SVG properties like we do now too?

Yeah this is definitely doable.

**Comment by ghostwords** [comment]
Closing for now. Happy to reopen if we decide to come back to this.

**Pull request closed without merging**
