### PR TITLE
Add breakage warnings

### PR DESCRIPTION
**Pull request by ghostwords**
To help with #2021, this adds a warning icon with a tooltip next to certain domains in the domain list in the popup and options pages. The warning is shown when toggling a "yellow" domain to "red", and upon popup/options load, when a domain that would have been "yellow" otherwise was previously set to "red" by the user.

Popup:
Screenshot from 2020-02-07 16:21:30

Options:
Screenshot from 2020-02-07 16:22:49

### CODE REVIEW

**Comment by ghostwords** [comment]
A few Selenium tests are failing because tracker list HTML changed a bit and the tests need to be updated. I'll fix the tests next week.

**Comment by andresbase** [comment]
Now that I was testing maybe change the bang sign to white instead of black? I feel like the dark color gets lost surrounded by red.

I don't see any issues other than that.

**Comment by ablanathtanalba** [comment]
> Now that I was testing maybe change the bang sign to white instead of black? I feel like the dark color gets lost surrounded by red.
> 
> I don't see any issues other than that.

Tried this locally and it's definitely easier to make out the bang mark when it's white, but off the top of my head I know that black text on red has a higher contrast ratio than white text does... I wonder if this would be an accessibility concern, making it white on red instead of black?

**Comment by andresbase** [comment]
Red and white seems to be the recommended: https://accessibility.psu.edu/color/colorvisiondetails/

**Comment by ablanathtanalba** [comment]
Nice! In that case, agreed with @andresbase

**Comment by ghostwords** [comment]
I updated all jQuery UI icons (the "i" icons under Tracking Domains, the Manage Data tab button icons, the add/remove buttons on Disabled Sites) to use an [icon font](https://mkkeck.github.io/jquery-ui-iconfont/).

The new warning icon in the popup:
Screenshot from 2020-02-10 14:26:17

On the options page:
Screenshot from 2020-02-10 14:25:44

**Comment by ablanathtanalba** [comment]
The new triangular shaped icons are a great change. They definitely give a clearer indication of warning than the previous ones did. The white exclamation point is way more clear than before -- good call, @andresbase . 

All LGTM!

**Comment by andresbase** [comment]
LGTM!

**Pull request merged**
