### PR TITLE
Improve handling of long domain names, upgrade tooltips

### LINKED ISSUE #1700: Long hostnames in list of blocked/allowed domains are trunacted. Unable to determine if I should unblock or not.
[Image showing the problem](https://snag.gy/IVjB6N.jpg)

The problem is that I cannot see what the full hostnames, and thus unable to determine which I want to unblock.

I've encountered the problem on the following link:
http://www.vg.no/nyheter/utenriks/spania/ni-sendt-til-sykehus-politiet-bruker-makt-for-aa-stanse-valget/a/24153514/

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #1700.

### CODE REVIEW

**Comment by ghostwords** [comment]
Before:
screenshot from 2017-10-02 11 09 58
After:
screenshot from 2017-10-02 11 10 09

**Comment by ghostwords** [comment]
New tooltips:
screenshot from 2017-10-02 13 29 36.

Should work better than old tooltips (can handle long/multiline strings, will no longer get hidden under other elements, HTML created and destroyed as needed instead of on list initialization).

Made a few places that used system tooltips use these new tooltips.

**Comment by ghostwords** [comment]
Since this updates translations, after merging, I have to push the source `en_US` locale to Transifex, pull it back down to get Transifex's sort/formatting, and then pull down all other locales to have them reflect the added and removed messages.

**Comment by ghostwords** [comment]
Tooltips over individual sliders are still buggy (you have to hover at the bottom edge of the slider to see the tooltip, the cursor switches from hand to pointer), but I think this is an existing bug, not a new one.

**Comment by ghostwords** [comment]
Another existing bug discovered during testing: #1706.

**Comment by andresbase** [comment]
On macOS Sierra Chrome 61:
 __Popup__
screen shot 2017-10-03 at 4 58 43 pm


Hand not seen but same thing you already mentioned about the border:
screen shot 2017-10-03 at 5 03 19 pm

__Options__
screen shot 2017-10-03 at 5 16 34 pm
When there is "-" it jumps to the next line, otherwise it's hidden under the toggle. Can also be seen in img1 for toggle.

screen shot 2017-10-03 at 5 14 35 pm

On macOS Sierra FF56
__Popup__
screen shot 2017-10-03 at 5 29 14 pm

__Options__
screen shot 2017-10-03 at 5 29 34 pm
screen shot 2017-10-03 at 5 29 54 pm

**Comment by andresbase** [comment]
On Windows 10

* Chrome 60 (having issues updating to 61)
Same as reported above
* Firefox 56
Same as above

**Comment by ghostwords** [comment]
Ah good point, I saw it but I didn't really see it. Domain name wrapping disabled.

**Pull request merged**
