### PR TITLE
Update French translations

### PR DESCRIPTION
**Pull request by samira-ouraga**

### CODE REVIEW

**Review by ghostwords — COMMENTED** [review]
Hello and thank you for your contribution!

The "description" strings should be left untranslated; they are meant to be translator hints. We should make this more clear in our [guide to translating Privacy Badger](https://github.com/EFForg/privacybadger/blob/master/doc/Translation.md).

**Comment by ghostwords** [comment]
Also, have you considered joining the [Privacy Badger team on Transifex](https://www.transifex.com/eff/privacy-badger/)?

**Comment by samira-ouraga** [comment]
> Hello and thank you for your contribution!
> 
> The "description" strings should be left untranslated; they are meant to be translator hints. We should make this more clear in our [guide to translating Privacy Badger](https://github.com/EFForg/privacybadger/blob/master/doc/Translation.md).

Fixed

**Review by ghostwords — APPROVED** [review]
Thanks again!

**Pull request closed without merging**
