### PR TITLE
Add cdn.polyfill.io to the yellow-list.

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by ghostwords** [comment]
Could you provide a few examples of where Badger decides `cdn.polyfill.io` is a tracker?

**Comment by JakeChampion** [comment]
help.ft.com is where I noticed it @ghostwords

**Comment by ghostwords** [comment]
This might be the result of a Privacy Badger bug responsible for incorrectly attributing localStorage/"supercookie" tracking to unrelated domains. If so, the fix is in progress in #1403.

Could you run the following JavaScript code in your Privacy Badger's background page console, and send me what it prints out?

```javascript
(function () {
  const STR = "polyfill";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

This should print the decisions your Badger reached for all "polyfill" domains, and also the site domains Badger saw "polyfill" domains perform tracking on.

To open Badger's background page console in your Chrome browser, visit "chrome://extensions", make sure "Developer mode" is checked (in the upper right), find the row for Privacy Badger, and click on the "background page" link in that row. Then, in the newly appeared window, make sure the "Console" tab is selected, click somewhere within the ">" prompt, paste the above JavaScript code, and press the Enter key.

**Comment by astronaut-wannabe** [comment]
@ghostwords I also see `cdn.polyfill.io` blocked (on http://mavo.io/demos/homepage/?storage=local)

running your script gives me the following output:

```js
**** ACTION_MAP for polyfill 
cdn.polyfill.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1496688914069
} 
polyfill.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492972850798
} 
polyfill.musicglue.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1495243417287
} 
**** SNITCH_MAP for polyfill 
polyfill.io [
  "sitepoint.com",
  "digitalocean.com",
  "mavo.io"
]
```

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.

**Pull request closed without merging**
