### PR TITLE
Improved NL Translation of messages.JSON

### PR DESCRIPTION
**Pull request by To3ts3nb0rd**
Finished the translation of the messages that were in the master. I did not understand the comment of ghostwords to get something from Transifex; is there a newer version of the messages there?

### CODE REVIEW

**Comment by ghostwords** [comment]
Are you referring to the following from our [current translations howto guide](https://github.com/EFForg/privacybadger/blob/5e68f6d2e5a0791817596007870afc11f5d4464d/doc/Translation.md)?

>Before starting your work, send a message to ghostwords, who will check if Transifex and GitHub translations are correctly synced. To send him a message, go to his profile and click on "Send message". This will help avoid translating something that has already been translated or that is currently being translated. Also, send ghostwords a message when you have finished your work so that he will upload your translation to GitHub.

This is a suggestion for translators who prefer to work in Transifex. Since I don't effectively get notified by Transifex, there is a chance of work being duplicated. One person works on translations in Transifex without realizing there is ongoing work on GitHub. This advice isn't guaranteed to avoid duplication, but it could help.

**Comment by ghostwords** [comment]
Thank you! Merged and pushed to Transifex.

**Comment by To3ts3nb0rd** [comment]
I also have one more question; I used the formal form of speaking to a person. Is that the preferred one? Or should it be the informal form of address? The English is ambiguous.

**Comment by ghostwords** [comment]
I see formal in [de](https://github.com/EFForg/privacybadger/blob/992b4781ee7538171f7a8c2cf2c5de3b918f6b1d/src/_locales/de/messages.json) and [ru](https://github.com/EFForg/privacybadger/blob/master/src/_locales/ru/messages.json). Formal seems right to me.

**Pull request merged**
