### PR TITLE
Add NYU domains to MDFP list

### PR DESCRIPTION
**Pull request by northgardner**

### CODE REVIEW

**Comment by bcyphers** [comment]
Has this caused any issues for you? I browsed around the sites a bit and didn't notice Privacy Badger blocking content or ID'ing resources from among NYU sites as trackers.

(We'd prefer not to add MDFP entries unless they fix a demonstrable issue.)

**Comment by northgardner** [comment]
Yes, we have had a couple demonstrable issues, that seem to happen because we
do front-end searches against Solr hosts on *.dlib.nyu.edu from websites
that are not in nyu.edu domain (such as site on  the nyupress.org domain.).

Jonathan

**Comment by bcyphers** [comment]
Thanks. Looks like there are some lint issues: https://travis-ci.org/EFForg/privacybadger/jobs/509630785#L467. Would you mind fixing those? After that it's good to go.

**Comment by northgardner** [comment]
Will do. Thanks.

**Pull request closed without merging**
