### PR TITLE
Make first party scripts conditional

### LINKED ISSUE #2025: First-party scripts should not run when privacy badger is disabled
Brought up in #2018. The Twitter and Facebook link-unwrapping scripts run even when privacy badger is disabled, and this could make it hard for users to figure out whether PB is breaking something on one of those sites. We should add a check for `badger.isPrivacyBadgerEnabled()` before running each script.

### PR DESCRIPTION
**Pull request by Jsnhlbr5**
Fixes #2025

### CODE REVIEW

**Comment by Jsnhlbr5** [comment]
All tests failed, presumably either because the background page doesn't exist in the test environment or because the test now checks too early (before the script actually runs due to the new messaging delay).  Any suggestions on how to modify the test to accommodate this?

**Comment by bcyphers** [comment]
Thanks for opening this!

The tests you probably need to fix are in https://github.com/EFForg/privacybadger/blob/master/src/tests/tests/firstparties.js. I'd try stubbing `chrome.runtime.sendMessage` to do what you want -- you can find examples of other stubbed global functions in the test file above.

**Comment by Jsnhlbr5** [comment]
The Firefox Beta Travis build seems to hang on a test that I have not affected (and that appears to hang on the current master branch as well); all other tests pass.

**Comment by ghostwords** [comment]
Tests hanging on Firefox Beta is tracked in https://github.com/mozilla/geckodriver/issues/1366; I'll have a workaround for it on master soon hopefully.

**Comment by Jsnhlbr5** [comment]
Now one of the Chrome Stable cookie tests failed?  If I'm reading the report right, it had some kind of timeout error.

**Comment by Jsnhlbr5** [comment]
The Travis build completed successfully, but for some reason that status hasn't propagated here yet.

**Comment by ghostwords** [comment]
I don't know if @bcyphers wants to review this some more, so I won't merge.

**Pull request merged**
