### PR TITLE
Add more Google domains to yellowlist

### LINKED ISSUE #1208: fusiontables.google.com blocks map
http://www.wickedlocal.com/news/20170212/where-guns-are----licenses-surge-in-brockton-region

`fusiontables.google.com` blocks the interactive map.

### LINKED ISSUE #1246: play.google.com breaks image of playstore
https://whispersystems.org/blog/

`play.google.com` breaks "Get it on Google Play" image.

### LINKED ISSUE #1254: trends.google.com
http://knowyourmeme.com/memes/based-stickman

`Search Interest` section
`Requests to the server have been blocked by an extension.`

Not sure if this would count as tracking. Good candidate for script surrogate?

### LINKED ISSUE #1300: sites.google.com breaks image
https://devs-lab.com/how-to-unbrick-hard-soft-bricked-google-huawei-nexus-6p.html

The image under `fastboot devices` is blocked by `sites.google.com`

### LINKED ISSUE #1313: books.google.com blocks images
http://paulburneyministries.com/how-to-be-a-bawse-a-guide-to-conquering-life/

`books.google.com` blocks images halfway down the page

### LINKED ISSUE #1317: video.google.com
https://www.facebook.com/permalink.php?story_fbid=1635086426815647&id=100009429163339

`video.google.com` breaks the video. Note that the video still doesn't load even without PB, however the player itself is blocked from even loading due to video.google.com. Thus this probably affects other similarly situated videos.

### LINKED ISSUE #1409: storage.googleapis.com blocks images
https://blog.google/topics/journalism-news/building-better-web-everyone/

`storage.googleapis.com` blocks images

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #1208
Fixes #1246
Fixes #1254
Fixes #1300
Fixes #1313
Fixes #1317
Fixes #1409

### CODE REVIEW

**Comment by ghostwords** [comment]
After review/testing, need to update legacy list, and then update both lists in production.

**Comment by cowlicks** [comment]
LGTM, should I wait for you to update the lists to merge?

**Comment by ghostwords** [comment]
Yeah? I'm not sure what the workflow should be yet. I'll wrap this up tomorrow, merge then, see how it goes.

**Comment by ghostwords** [comment]
OK, [yellowlist](https://www.eff.org/files/cookieblocklist_new.txt) and [legacy yellowlist](https://www.eff.org/files/cookieblocklist.txt) updated.

**Pull request merged**
