### PR TITLE
Add title as full URL atttribute for Twitter profile links

### PR DESCRIPTION
**Pull request by rugk**
Fixes https://github.com/EFForg/privacybadger/issues/1426

twitterprofile

Some things I noticed as for the current implementation:
* I don't understand why you need two loops
* Also why is the selector query so specific if you filter out the elements later anyway?
* The above combined, this could easily be simplified into only one loop for all t.co elements
* Why does the query include **http**://t.co links? Does Twitter use them anywhere, anyway? AFAIK they are HTTPS-only for some time already, are not they?
   **Edit:** Saw https://github.com/EFForg/privacybadger/pull/1392#issuecomment-304400706, but don't know whether that is valid for profile links. Anyway, who cares… 

I read https://github.com/EFForg/privacybadger/pull/1392#issuecomment-307234848 and saw that you want to avoid `title` due to XSS issues. (Unfortunately I read it a bit late but huh… 😇)

So my implementation always prefers the expanded data thing attribute, and only falls back to the `title` if that is not possible (as in the twitter profile), and as it has been the case before, it checks that it is a valid HTTP/HTTPS URL, so I see no direct attack/XSS vector here.

As for this PR:
* I did not test it works when an URL is mentioned in the Twitter bio. Should I? (if so an example link would be nice – I want to avoid changing my bio because of that :laughing:)
* If the above XSS thing does not convince you, I could of course make it more specific to only target the "website" part in the bio, where hopefully Twitter verifies that users cannot put bad things into the `title` tag. (this change would of course be contrary to the previous point, so mhh… only one thing possible here)

BTW I plan to also do https://github.com/EFForg/privacybadger/issues/1886. If I've got nothing to do I could have a look at https://github.com/EFForg/privacybadger/issues/1651, but I'd need to signup on Tweetdeck for that and I also see that a PR is open anyway for that (but abandoned, as it seems).

/cc @cowlicks, @ghostwords

### CODE REVIEW

**Comment by ghostwords** [comment]
Thank you, I'll be taking a look at this in a bit. I'll also come back to #1872, it was blocked by a Firefox issue but it seems to have been resolved.

**Comment by rugk** [comment]
Oh, I already see the code conflicts coming. But I can integrate https://github.com/EFForg/privacybadger/pull/1872, and then likely also https://github.com/EFForg/privacybadger/issues/1886, into this PR, if wanted.

**Comment by bcyphers** [comment]
To answer your question about the two loops (and because I was curious too):

Some links don't have any attributes that contain their real URLs. Specifically "cards" that look like this:
twitter-link-card-example

The HTML for that element is:
```
<a class="js-openLink u-block TwitterCardsGrid-col--12 TwitterCard-container TwitterCard-container--clickable SummaryCard--large" href="https://t.co/E4MZwXxcjq" rel="noopener" data-card-breakpoints="w500 w450 w400 w350 w300 w250 w200 w150 w100 w50 ">
...
</a>
```

No unwrapped URL in sight.

BUT, for whatever reason, there is another, hidden element on the page that has the exact same t.co link along with the correct unwrapped link. In this case:

```
<a href="https://t.co/E4MZwXxcjq" rel="nofollow noopener" dir="ltr" data-expanded-url="https://theatln.tc/2rDqivR" class="twitter-timeline-link u-hidden" target="_blank" title="https://theatln.tc/2rDqivR"></a>
```

So, in our script, the first loop finds the hidden `<a>`, replaces the t.co `href` with the correct one, and stores the {t.co -> original URL} mapping in `fixes`. Then, once all the `data-expanded-url` links have been processed, our function goes back through _every_ t.co link on the page to see if we can unwrap any more. This seems to catch pretty much everything in the feed.

**Comment by bcyphers** [comment]
If there is an issue with XSS (though I'm not sure there is), why not just make the selector specific to the profile by using `.ProfileHeaderCard a`?

**Comment by rugk** [comment]
So what to do?

**Comment by ghostwords** [comment]
I suggest following the advice in https://github.com/EFForg/privacybadger/pull/1392#issuecomment-307234848: instead of modifying and complicating existing link scanning code, let's have a single dedicated query for the Twitter profile link. The profile link is a special case so let's treat it as one.

**Comment by ghostwords** [comment]
As for security implications of trusting the title attribute ... Is the idea that `title` will look like `javascript:...` while the `t.co` link points to some valid URL? Aren't titles auto-generated from destination URLs though?

**Comment by rugk** [comment]
Okay, did so. BTW I also did some code-cleanup. I did it in separate commits, so you could revert them if wanted, though. (e.g. if you do not like constants :wink:). You can stash the commits later.

**Pull request merged**
