### PR TITLE
Fix popup layout for overflow menu in Firefox

### LINKED ISSUE #1120: "Pin to Overflow Menu" / "Move to Menu" breaks popup layout in Firefox
## Steps to Reproduce

1. Install Privacy Badger on a machine running macOS and Firefox 50+
1. Right click on the Privacy Badger icon in the toolbar and select "Move to Menu"
1. Open the menu and click the Privacy Badger icon
1. Observe a broken layout for the controls

## Expected Behavior

- Layout should adjust to fill given space that is roughly 40 pixels narrower than what is allocated

## Screenshots

screen shot 2017-01-04 at 11 55 19 am

screen shot 2017-01-04 at 11 53 51 am

screen shot 2017-01-04 at 11 53 37 am

### PR DESCRIPTION
**Pull request by generalbrus**
Fix #1120 by setting ad-hoc styles for the popup shown from the overflow menu.

One odd thing I've noticed, and maybe you can check if it happens to you as well: the *first* time the popup is opened from the overflow menu, the popup is wider than it should be and there is a blank space on the right. Screenshot:

a1q5ftfstqc_lgigometgw

From then on the popup is shown correctly.
Also, the problem is not present if the option "disable popup auto hide" is set. It looks like firefox is not updating the width of the popup fast enough.

### CODE REVIEW

**Comment by bcyphers** [comment]
Can't repro the original issue on Ubuntu 18.04, but there's a different issue here: 
generalbrus-fix-bug (both in this branch and in master).

I'll try this on a Windows machine at home tonight and get back to you.

**Comment by generalbrus** [comment]
@bcyphers your popup seems to be normal width. At least on my system (macOS), if I pin the extension to the overflow menu (probably called only "menu" in earlier Firefox releases), the popup is shrunk, which caused some layout issues.

About the scroll bar - do you want to hide it when the user is not scrolling?

**Comment by bcyphers** [comment]
Sorry for the delay. Yes, the issue I pointed out above is different, and the problem this PR is trying to address was never a problem on Ubuntu. It would be great if we could fix both problems with one PR, but maybe they're too unrelated.

The original issue isn't fixed for me in Firefox on Windows 10:
pb-firefox-broken

**Comment by bcyphers** [comment]
The test failure here looks unrelated to the changes. @ghostwords have you seen this before? https://travis-ci.org/EFForg/privacybadger/jobs/428562652

**Comment by ghostwords** [comment]
The same test failed once (also with Firefox) in another PR: https://travis-ci.org/EFForg/privacybadger/builds/429624697. I don't remember seeing this before though.

**Comment by ghostwords** [comment]
Hi @andresbase, could you check this PR on Firefox for Android please? There should be no changes. Would be great to confirm on Firefox/Chrome on macOS too; no changes to the popup in either browser by default, but the popup be fully usable now when placed in the overflow menu on Firefox.

**Comment by bcyphers** [comment]
@ghostwords I finally got the android test setup working, and this looks fine.

**Comment by ghostwords** [comment]
Thanks again!

**Comment by DJCrashdummy** [comment]
#1120 seems to be fixed now. thank you! :+1: 
but as shown in https://github.com/EFForg/privacybadger/issues/2146#issue-353268000 the last "banner/button/link" is still cut off.

**Comment by ghostwords** [comment]
Please subscribe to #1077 for the clipped buttons bug.

**Pull request merged**
