### PR TITLE
Move yellowlist into src/data/

### PR DESCRIPTION
**Pull request by eenblam**
This PR moves the cookie block list into the source directory so that it can be built with the extension. If necessary, linting can be added to the build.

Also updated:
- Makefile push of yellowlist to EFF
- Script to generate legacy cookie list from modern cookie list

### CODE REVIEW

**Comment by ghostwords** [comment]
Could we rename the local files to "yellowlist"?

**Comment by ghostwords** [comment]
Related to #1487.

**Comment by ghostwords** [comment]
We could also remove the "legacy" file from the repo, instead of generating a temporary legacy file using `scripts/legacy-cookies.sh` at the time I run `make upload`. It's a bad idea to have that file be manually updated by contributors, and no need to lug it around really.

**Comment by eenblam** [comment]
@ghostwords The legacy file is currently used in tests. Deleting it means updating the build process as well.

https://github.com/EFForg/privacybadger/blob/363ecda7ad65e053c1deecd040c48701c6061d97/tests/selenium/pbtest.py#L226

**Comment by ghostwords** [comment]
Yep, let's remove `cookieblocklist_path` and `test_cookieblock_format`.

**Comment by ghostwords** [comment]
Thanks!

**Pull request merged**
