### PR TITLE
Ask about other extensions when reporting errors

### PR DESCRIPTION
**Pull request by ghostwords**
This adds another input to the error reporting form. The input's placeholder asks the user to share what other extensions they have installed. We already have an "extensions" column on the error reports table; it's just that it's always `NULL`.

This PR also sets focus on the problem description input upon error reporting overlay activation, as well as moves the "what else gets sent with your report" notice up above the submit button.

There are existing issues with form height (seemingly worse in Firefox). The height of the error form is affected by translations. The form can get taller than popup height, which will generate a scrollbar in Firefox, but not Chrome. The scrollbar is visible regardless of whether the form is active or not. If this PR doesn't make these problems worse, I'm fine leaving them unaddressed for now.

### CODE REVIEW

**Comment by ghostwords** [comment]
OK, this does seem worse on pages with short popups (few or no third-parties), especially in locales with longer messages:

English:
screenshot from 2018-04-25 12 30 40

German (ignore the missing placeholder):
screenshot from 2018-04-25 12 32 07

**Comment by ghostwords** [comment]
Ideas/patches welcome!

**Comment by andresbase** [comment]
We might want to make it clearer that these fields are optional. something like:
`[Optional] What went wrong?`
`[Optional] What other extensions do you use?`

We should also link to our privacy policy in that for example:
`... sliders for this site. [Privacy Policy]`

How about reducing the boxes to two lines?

**Comment by ghostwords** [comment]
Looking at this again, I kind of regret removing the label in 78afa86aaaab9549f164b3a63a1c837be1f12fd2.

We shouldn't be constrained by the small amount of space available in the "no domains" scenario. If the popup's height isn't enough, we could enlarge it to fit the error reporting form when the form is requested (restoring the original height when the form closes/is closed).

We could also designate a minimum height for the popup that is larger than current minimum height, one large enough to fit the error reporting form (in all locales).

**Pull request closed without merging**
