### PR TITLE
Localise social button tooltip

### LINKED ISSUE #1439: Translations for replaced Facebook button
When hovering the replaced Like button the text "PrivacyBadger has replaced this FacebookLike button" appears. Shouldn't "PrivacyBadger" and "FacebookLike" be "Privacy Badger" and "Facebook Like button"? Could these strings also be translated in Transifex?

privacybadger

### PR DESCRIPTION
**Pull request by mijiturka**
Resolves #1439.

* Replace hardcoded tooltip with two localised messages.
  In languages like Spanish, where "Facebook" has to come at the end of the sentence, the second
  message could just be left as a dot
* Added untranslated new messages to all languages' locale files.
* Translated new messages for Bulgarian and Spanish.
* Changed the Spanish translation for the options widget message too. "Vuelva a colocar" literally
  means replace as in "place again", what we need here is "sustituir", as in "substitute"

### CODE REVIEW

**Comment by ghostwords** [comment]
Nice, thank you! Will fully review later. Some notes for now:

Does this fix #1439?

I thought for some reason `chrome.i18n` doesn't work inside content scripts, but if it works fine, great, less code to make it work.

There is no need to manually add untranslated copies of new messages to each locale as I'll auto-generate them while syncing translations with Transifex after the PR passes review. I wonder where we should document this.

The test failures don't seem related to this PR; something for me to keep looking into.

**Comment by mijiturka** [comment]
Thanks, I've added the issue number in the description now.
This may be a good place to document the addition of new messages: https://github.com/EFForg/privacybadger/blob/master/doc/Translation.md . Should I remove the extra untranslated messages?

**Comment by ghostwords** [comment]
Yes please!

**Comment by ghostwords** [comment]
The `test_trackers_link` exception should be fixed with the latest updates to master.

**Comment by ghostwords** [comment]
Documented handling new localized strings in the [translations guide](https://github.com/EFForg/privacybadger/blob/master/doc/Translation.md#a-note-about-adding-translation-strings-in-prs).

**Comment by ghostwords** [comment]
Thank you! Merged and synced with Transifex.

Follow up commits: https://github.com/EFForg/privacybadger/compare/42277b34fc3ec2f334dca9a857dee468fb8c0bec~3...42277b34fc3ec2f334dca9a857dee468fb8c0bec

**Pull request merged**
