### PR TITLE
Don't detect CentralAuth

### PR DESCRIPTION
**Pull request by thecutefinder**
See the comments in my proposed change for why.

### CODE REVIEW

**Comment by thecutefinder** [comment]
Apologies for the large group of pull requests. I've been having difficulties merging these into one request.

**Comment by ghostwords** [comment]
Is this the same problem as #2877? Does moving the slider for `login.miraheze.org` to "block cookies only" work around the problem? Are there other breakages beyond `login.miraheze.org`?

**Comment by thecutefinder** [comment]
See the reply there for more information on the slider options.

The same problem will likely occur for any MediaWiki wikifarm or group of affiliated MediaWiki wikis using the CentralAuth extensions with more than 3 custom domain wikis (this is almost every wikifarm except Fandom).

**Comment by ghostwords** [comment]
Is this another instance of the ["login cookies"](https://github.com/EFForg/privacybadger/issues?q=is%3Aissue+label%3A%22login+cookies%22+) bug? I think rather than make one-off hacks we should consider how to avoid this category of issue wholesale.

**Comment by ghostwords** [comment]
Could you open a new issue for the CentralAuth problem?

**Comment by thecutefinder** [comment]
Okay, got it.

**Pull request closed without merging**
