### PR TITLE
Fix: Block Kick.com widget

### LINKED ISSUE #3019: Kick.com stream/video widget not replaced
The Stream/Video Widget for Kick.com is not being replaced, like other widgets.

image

### PR DESCRIPTION
**Pull request by Stupidoodle**
Added kick.com to socialwidgets.json
Fixes #3019

### CODE REVIEW

**Comment by ghostwords** [comment]
Hello and thank you for the PR! Could you share links to pages that contain this widget? The more distinct sites, the better. One link per each different site is good.

**Comment by Stupidoodle** [comment]
Its only player.kick.com

Source: https://www.streamweasels.com/how-to-embed-kick-live-streams-on-any-website-2023/

"<iframe src="https://player.kick.com/bige" style="width:100%;aspect-ratio:16/9"></iframe>"

**Comment by ghostwords** [comment]
I am looking for examples of pages that include this Kick Player widget. Like, https://example.com/some/page/that/includes/kick/widget.html but for real. Multiple different sites would be great.

**Comment by ghostwords** [comment]
I need to see examples of this widget in the wild before I can add it to Privacy Badger.

**Comment by ghostwords** [comment]
By the way, widget replacement only makes sense for situations when widgets from one company are embedded on websites belonging to other companies/organizations/people. Privacy Badger will only replace embedded Twitch streams on other people's websites, not on Twitch itself since there is no point to blocking and replacing Twitch on Twitch.

**Comment by Stupidoodle** [comment]
Ah I see what you mean, sorry I didnt understand properly.

So I saw it on the wild on chess.com

**Pull request closed without merging**
