### PR TITLE
Fix cookie tracker detection

### LINKED ISSUE #1245: Fix test_cookie_tracker_detection in Firefox
Currently [failing on master in Firefox](https://travis-ci.org/EFForg/privacybadger/jobs/210598442). Was disabled when [Selenium tests in Firefox were merged](https://github.com/EFForg/privacybadger/commit/e517a49), re-enabled as part of https://github.com/EFForg/privacybadger/pull/1205 (`git bisect` seemed to lead me to 936a1f8908a8ff2b3c784d8e6a86b05e4210eaaa), but isn't working still:
```
________________________________ CookieTest.test_cookie_tracker_detection ________________________________
...
>               window_utils.close_windows_with_url(self.driver, self.popup_url)
selenium/cookie_test.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

...
>       raise Exception("was not able to find window for url " + url)
E       Exception: was not able to find window for url moz-extension://37702c80-1338-4638-b07a-33e87fa5327d/skin/popup.html
selenium/window_utils.py:54: Exception

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #1245.

### CODE REVIEW

**Comment by ghostwords** [comment]
@pde @cooperq @cowlicks So this **was** a Privacy Badger bug! Header names are case-insensitive, and cookie tracking detection code wasn't normalizing header names: f0a0fb937c617595f719dbbef3534547566d8e04. The consequence Privacy Badger doesn't detect cookie tracking any time the cookie tracker header is lowercase. Which seems to happen consistently for this test in Firefox.

**Comment by ghostwords** [comment]
TODOs:
[ ] Add some unit tests.
[ ] Check why the `test_cookie_tracker_detection` test was passing in Chrome.
[ ] Clarify scope of breakage.

**Comment by cowlicks** [comment]
Yikes! It would be good to understand how strict browsers are with accept `Set-Cookie` header. And if browsers always send cookies with a `Cookie` header. Could we be missing header names with whitespace in them? Or headers using an em dash instead of a normal dash like `Set–Cookie`. Ideally we'd have an internal browser function to validate this since diverging from its behavior could lead to some XSS or header injection.

**Comment by cowlicks** [comment]
Apparently http header field names are supposed to be case-insensitive. https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by ghostwords** [comment]
It seems like header handling changed in Firefox somewhere between versions 47 and 52. A fresh install of Privacy Badger from AMO starts blocking after three newspaper sites on 47, but not on 52.

Note that you have to manually clear Badger's storage if you reuse the profile, as uninstalling Firefox extensions doesn't perform proper cleanup. Might be easier to use a new profile for each test.

**Pull request merged**
