### PR TITLE
Update Swedish translations

### PR DESCRIPTION
**Pull request by ghostwords**
@jony0008 @Dyras Could you take a look please? I pulled in the latest from Transifex (and auto-sorted the file by message key). We have a few untranslated strings at this point (the source file in Transifex was out of date) but that's OK.

### CODE REVIEW

**Comment by jony0008** [comment]
@ghostwords I have taken a look and made some small changes and translated the untranslated strings, please pull the latest changes from Transifex. I also noticed that some of the descriptions in the JSON file was not translated in Transifex.

**Comment by ghostwords** [comment]
Cool, thank you! OK will do.

I don't think we need to translate descriptions as they are meant to be translator aids and not for end users in any way. We should document this when we document the translations process ...

**Comment by ghostwords** [comment]
Updated. I added a space to `badger_status_allow` and `badger_status_noaction` to match the English versions. I think we use that space in the UI. We should make these sort of messages less fragile at some point, maybe as part of https://github.com/EFForg/privacybadger/issues/1329/

**Comment by jony0008** [comment]
Corrected two small typos

**Comment by ghostwords** [comment]
Pull request updated.

**Comment by ghostwords** [comment]
So I'll merge this soon and push the "sv" locale to Transifex (to fix the two messages with missing spaces and to see if sorting is preserved or not)?

**Comment by jony0008** [comment]
@ghostwords Sounds good

**Comment by ghostwords** [comment]
Merged. Thank you for the updates!

**Comment by jony0008** [comment]
@ghostwords Thank you!

**Comment by jony0008** [comment]
@ghostwords Corrected 2 more typos.

**Comment by ghostwords** [comment]
@jony0008 Got it, updates are in #1442.

**Comment by jony0008** [comment]
@ghostwords Corrected 2 more typos.

**Comment by jony0008** [comment]
@ghostwords 1 mistake, please update again.

**Comment by ghostwords** [comment]
@jony0008 Updated!

**Comment by jony0008** [comment]
Please update again, I found a word that needed to be changed

**Comment by ghostwords** [comment]
Updated: 9ebc49c624e57a2e6c5a3b75871d4ddee320110c.

**Comment by jony0008** [comment]
@ghostwords I changed to use the plural form for "potential" in Swedish translation because it is almost always used in that form

**Comment by ghostwords** [comment]
Updated: ae4cd82ad18a885e8f5e68a47ecc922f3de61c20.

**Comment by jony0008** [comment]
@ghostwords Please update again

**Comment by ghostwords** [comment]
Was it about "whitelisted_domains"? Sorry, I pushed something early to Transifex. Anyway, I don't see any changes for `sv` to commit.

**Comment by jony0008** [comment]
Yes it was about "whitelisted_domains".

**Comment by jony0008** [comment]
@ghostwords I translated the new Tracking Domains string

**Comment by ghostwords** [comment]
Thank you! Updated with a264c1d1c526008d98625acfed13adad3ae2e1ec.

**Comment by jony0008** [comment]
Hi, thanks for adding the strings to Transifex, I have translated them.

**Comment by ghostwords** [comment]
Thanks! Updated: dba0447ba7577f9b9c7da7e6fca1145164593357.

**Comment by jony0008** [comment]
I have translated more strings.

**Comment by ghostwords** [comment]
Cool, thank you! I'll pull them in next week.

**Comment by ghostwords** [comment]
Updated (30014bd74a81551e2df759ad181d057f775b0d00), thank you!

**Comment by jony0008** [comment]
Please update to add the new translated string

**Comment by ghostwords** [comment]
Thank you! Updated in 5e68f6d2e5a0791817596007870afc11f5d4464d.

**Comment by jony0008** [comment]
I have translated the new strings. Please update!

**Comment by ghostwords** [comment]
Updated in https://github.com/EFForg/privacybadger/commit/29469c37d4c8c4f603e7ee0068d3580f4e09d0ce#diff-8430fadcdf987bf0d5702e49d8425c67. I fixed missing spaces [here](https://github.com/EFForg/privacybadger/commit/29469c37d4c8c4f603e7ee0068d3580f4e09d0ce#diff-8430fadcdf987bf0d5702e49d8425c67R175) and [here](https://github.com/EFForg/privacybadger/commit/2f1acd554e311bb6600cd96700a427b317f113c5#diff-8430fadcdf987bf0d5702e49d8425c67), an unfortunate translations complication caused by not yet being able to make use of translations placeholders (https://github.com/EFForg/privacybadger/issues/1329#issuecomment-332311249).

**Comment by jony0008** [comment]
@ghostwords Please update again

**Comment by ghostwords** [comment]
Updated (dd3b378714c14f417b06a591e73cd1273acb1f16), thanks!

**Comment by jony0008** [comment]
@ghostwords Please update again

**Comment by ghostwords** [comment]
[Done](d2b5553711de3d4ff6614eecf573eb5c2e744544), thank you!

**Comment by jony0008** [comment]
@ghostwords Please update again and read my issues on Transifex

**Comment by ghostwords** [comment]
[Updated](https://github.com/EFForg/privacybadger/commit/dd4e9487a54a78888a4957989d7010b4d189b155) (and responded), thank you!

**Comment by jony0008** [comment]
@ghostwords Please update again.

**Comment by ghostwords** [comment]
Thanks! Updated in 0e74a1c3e91ad084529705c7fa9dd5d26a805381, left some questions in Transifex.

**Comment by jony0008** [comment]
@ghostwords I made some corrections, please update again

**Comment by ghostwords** [comment]
Updated: e4a689478d7806b583bd92ae9864ba10a854a0f0.

**Comment by ghostwords** [comment]
Thank you! 6aa7f09cd3e0d65207ca7e824e4b9b8210a54856

**Comment by ghostwords** [comment]
Done: e611057444faf8d50491a7bb6105eae46cf64ac5. Thanks!

**Comment by jony0008** [comment]
@ghostwords Please update again

**Comment by ghostwords** [comment]
Thank you! Updated in 026bcd23cac077227f2a152e2a7d16dfcb4c8286.

**Comment by jony0008** [comment]
@ghostwords Please update

**Comment by ghostwords** [comment]
Updated: 99452c3ae803febbb9c07c09ffb4b71b2aa9afe7.

**Comment by jony0008** [comment]
@ghostwords Please update

**Comment by ghostwords** [comment]
Updated: 0f5d881396f10d584465bb8224bce8fc1ba7926b. Thanks!

I left a question for you in Transifex.

**Comment by jony0008** [comment]
@ghostwords Please update

**Comment by ghostwords** [comment]
Already updated: 18889e65414b730c80f3d774c2f5490a9e4afa11.

**Comment by jony0008** [comment]
@ghostwords Please update

**Comment by ghostwords** [comment]
Done (7ab1c7abac31fa426d99283e9563be109cdb87da), thank you!

**Comment by jony0008** [comment]
@ghostwords Please update

**Comment by ghostwords** [comment]
Ah, turns out that message was really used, so I removed it: 7dbb6a570a9d2b90035b3321e781c734b335e442

**Comment by jony0008** [comment]
@ghostwords Ok. Please update again.

**Comment by ghostwords** [comment]
Done (ddd7b493a594ec5a80c1a86a9a9e703bb52d81e7), thanks!

**Comment by ghostwords** [comment]
Thank you! (527d31bfaa88f53f5773c96459e17699bb04c513)

**Comment by jony0008** [comment]
@ghostwords Please update

**Comment by jony0008** [comment]
@ghostwords Please update

**Comment by ghostwords** [comment]
[Updated](https://github.com/EFForg/privacybadger/commit/a7179cb66ff3c0d575b756dddd17e6b00c3f07a7#diff-8430fadcdf987bf0d5702e49d8425c67). Thank you!

**Comment by jony0008** [comment]
@ghostwords Please update

**Comment by ghostwords** [comment]
[Updated](124acccbd2011ad5f542251af9e24d244e34cedc), thanks!

**Comment by jony0008** [comment]
@ghostwords Please update

**Comment by ghostwords** [comment]
Updated: 19169d37fabe2c65730b1a207c09ec931bcf4f5d

**Comment by jony0008** [comment]
@ghostwords Thank you. Can you please update again. Should I still write here when I have made changes or will you update anyway?

**Comment by ghostwords** [comment]
Updated: 09b24b7ee0fabb619ce12eb955c99da647972c8f.

Hmm. I do check whether there are any Transifex updates pretty regularly. I guess you could ping me only if you don't see your changes show up here promptly enough.

Thanks for all your work!

**Pull request merged**
