### PR TITLE
Telegram.org multidomain first parties

### PR DESCRIPTION
**Pull request by theel0ja**
image

Links to broken sites:
* https://t.me/durov/76
* https://telegram.me/durov/76

### CODE REVIEW

**Comment by theel0ja** [comment]
This fixes only t.me and telegram.me, but Telegram widgets are broken.

Demo: https://rawgit.com/theel0ja/e5c0c4f20a02478330be49b4fc6a2214/raw/ceabcfa2980fe7b818f18b0bc361e1f6ef6806da/telegram-widget-demo.html

image
and widgets aren't showing up.

**Comment by ghostwords** [comment]
Do you know of any live examples of Telegram widgets? We would probably want to add a new replacement widget (#1467) or add the relevant domain(s) to the yellowlist. Regardless, we should continue this in a new issue or pull request.

**Comment by theel0ja** [comment]
Making an issue...

**Comment by theel0ja** [comment]
https://github.com/EFForg/privacybadger/issues/2029

**Pull request merged**
