### PR TITLE
Add content.jwplatform.com to yellowlist

### LINKED ISSUE #1030: jwplatform video broken
http://mashable.com/2016/11/07/reborning-babies/#EIhpNz8Wiaqp

`content.jwplatform.com` breaks the video. Move to yellowlist.

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #1030.

### CODE REVIEW

**Comment by cowlicks** [comment]
@ghostwords Can this go in for tomorrow? Sorry I forgot about it.

**Comment by ghostwords** [comment]
No problem! Cool, let's release it next Monday though along with any other yellowlist updates we'll get to. Just so we don't change too much stuff at the same time.

**Comment by terrorist96** [comment]
Wasn't this supposed to be included in today's release?

**Comment by ghostwords** [comment]
No sorry, the release got pushed back to today, and I'd rather not release yellowlist updates at the same time.

**Pull request merged**
