### PR TITLE
move migration code to migration

### PR DESCRIPTION
**Pull request by cooperq**
removes legacy migration from background script. places it in migration path. cc @ghostwords

### CODE REVIEW

**Comment by cooperq** [comment]
@ghostwords I tested this and the migration still works. I don't know what was wrong with my testing last time but I was unable to reproduce the previous failure case. Possibly a bug within firefox that has been fixed?

**Comment by ghostwords** [comment]
Is it time to restore that [integration test we disabled](https://github.com/EFForg/privacybadger/pull/1002/commits/822d804e5a4c95b147968118e76b0e0a8e4d59ab) in the original [Firefox Web Extensions migration pull request](https://github.com/EFForg/privacybadger/pull/1002)?

**Comment by ghostwords** [comment]
One change here is that while we are reverting making [Privacy Badger constructor's initialization asynchronous](https://github.com/EFForg/privacybadger/pull/1002/commits/8b5e5259d6fdf41ec3c6402308227e6e1b9eb012?w=1#diff-961641dd6af66f5e3313307cf4eb8f1d), we are making the Firefox WebExt migration asynchronous (it was previously synchronous in regard to `Badger` initialization). Does this introduce any issues?

**Comment by ghostwords** [comment]
So other than the test and the potential issues caused by something else happening while the Firefox migration is half-done, this looks OK.

I actually recommend blanking out the migration completely if 98% of Firefox users migrated already. Less code (always good) and much less potential for breakage.

Merging this is OK too ... But I would spend some time considering (and testing/simulating) the async interaction. Make the migration always trigger and emphasize the async aspect (by adding extra delays) and see if anything breaks.

**Comment by cooperq** [comment]
@ghostwords this is ready for a final review

**Comment by ghostwords** [comment]
Looks good, merged.

**Pull request merged**
