### PR TITLE
Script surrogation is broken for just-blocked-based-on-outgoing-headers domains

### PR DESCRIPTION
**Pull request by cowlicks**

### CODE REVIEW

**Comment by ghostwords** [comment]
As documented in https://developer.chrome.com/extensions/webRequest:

>Depending on the context, this response allows cancelling or redirecting a request (onBeforeRequest), cancelling a request or modifying headers (onBeforeSendHeaders, onHeadersReceived), and cancelling a request or providing authentication credentials (onAuthRequired).

**Comment by ghostwords** [comment]
This should be an issue instead.

**Comment by cowlicks** [comment]
@ghostwords Would you mind more explaining  more about why this was closed? Why create a separate issue instead of discussing here? Is there a benefit of leaving this code in?

My understanding of this is we block instead of surrogate in the one case where the script surrogate itself causes the 3rd strike. This seems like a rare case, with little impact, especially considering how few surrogates we have. Is there something else you think it might impact?

**Comment by ghostwords** [comment]
Pull requests are for when we know what needs to be done. We don't yet know what needs to be done here, or even what the issue is. All we know is that a block of code probably doesn't work the way we want it to.

**Pull request closed without merging**
