### PR TITLE
Stop first time message from stealing focus

### PR DESCRIPTION
**Pull request by serv-inc**
See decentraleyes at https://github.com/Synzvato/decentraleyes/blob/master/core/main.js#L79. (this is such minor change that I did not run the tests locally. As of https://github.com/EFForg/privacybadger/blob/master/doc/tests.md, Travis does this, right?)

### CODE REVIEW

**Comment by ghostwords** [comment]
Hello! Why would we want to hide the welcome page though? It seems more important to have as many people see the new user introduction as possible (right at the time of Badger installation, probably the best time to make the introduction) than to reduce the potential annoyance of having the introduction pop up in front of you.

**Comment by serv-inc** [comment]
Hello!

Users would still see the introduction page. The only difference is whether it would be right in front of their eyes, or a tab that they can eventually look at.

The old way, it can happen that you start typing in the location bar, and the extension opens a new tab and steals focus. This has happened to me several times.

If you do not steal focus, the user is still free to see the page at her leisure. As privacy badger works out of the box, and does not require configuration, this seems to be an UI improvement. Decentraleyes has a similar audience, and similar configuration requirements.

Still, feel free to not merge the pull request. Another approach would be to add a managed storage setting so that the extension can be pre-configured to not show the message. Whichever way you decide, thanks for the reply.

**Comment by ghostwords** [comment]
>The old way, it can happen that you start typing in the location bar, and the extension opens a new tab and steals focus. This has happened to me several times.

Which browser do you use? Can you talk more about when this happens? (Is this right after installing Privacy Badger, or right after restarting the browser?) I'd like to understand why you ran into this annoyance several times.

You stop getting the intro on restart once you either scroll down a bit in the intro page, or dismiss the intro reminder ("To learn how Privacy Badger works, click below for a quick tutorial.") in Badger's extension popup.

**Comment by serv-inc** [comment]
> Which browser do you use? Can you talk more about when this happens? I'd like to understand why you ran into this annoyance several times.


As web browsers seem the most insecure part of today's computers, the setup has the web user on `/tmp`. It is recreated every reboot. The install happens via Chrome's managed policies: There is a file, say `/etc/chromium-browser/policies/managed/config.json` which contains the following lines

```json
{
    [...]
    "ExtensionInstallForcelist": [
        [...]
	"pkehgijcmpdhfbdbbnkijodmdjhbjlgp;https://clients2.google.com/service/update2/crx"
    ]
}
```
(just remove the `[...]` to get valid json).

This happened with Chromium on LUbuntu. It even steals focus from other programs, e.g. the Terminal.

> Edit: The intro should only be shown once, immediately following installation.

It happens once only per installation, but if installation happens frequently ...

**Comment by ghostwords** [comment]
Ah, thank you for explaining!

>Another approach would be to add a managed storage setting so that the extension can be pre-configured to not show the message.

I think this is the right approach. Let's add support for setting Badger preferences (including the hidden "show first run page" preference) via [Chrome Group Policies](http://www.chromium.org/administrators/configuring-policy-for-extensions). I'll be happy to help figure out how to make this happen.

Previously: #1206

Here are the uBlock Origin docs for this feature: https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin

**Comment by serv-inc** [comment]
Awesome.

Could you point out where in the source the firstrun check should happen? (It was not clear to me where `POPUP_INITIALIZED` is saved, or should it be done somewhere else?)

Is it ok if only this is added as a managed storage first, and you can add other options later? Do you need to integrate this with the UI (this would make it much more intricate, and seems unneeded for a first-run-nag policy).

**Comment by ghostwords** [comment]
We should probably keep it maximally simple and just see on Badger startup if managed storage exists, and if it does, overwrite whatever local settings were defined in managed storage.

I think once we have code to overwrite one setting, extending it to overwrite more settings will be easy.

The new user intro page is currently gated behind `isFirstRun`, but this flag also controls whether to load seed data, and we want to keep one but not the other. So we should add a new hidden preference that when set will prevent the new intro page from being opened while leaving the rest to function as it does now.

I don't think we need any UI for this feature. We should document/advertise it somewhere though, maybe in the [FAQ](https://www.eff.org/privacybadger/faq).

**Comment by ghostwords** [comment]
Probably going to want to add the managed storage lookup/overwriting to the `BadgerPen` constructor.

**Comment by ghostwords** [comment]
`POPUP_INITIALIZED` isn't related to the new user intro page.

**Comment by serv-inc** [comment]
> We should probably keep it maximally simple 

done. See https://github.com/EFForg/privacybadger/pull/2215.

**Pull request closed without merging**
