### PR TITLE
Improve instruction messages in popup and options

### LINKED ISSUE #1211: Don't show "These sliders ..." text in popup when there are no sliders.
When there are no third party resources, don't show this message. Here is an example from eff.org. Maybe instead it should say something nice like "wow such privacy".

screenshot from 2017-02-16 11-57-09

### LINKED ISSUE #1443: Translation issues with "Privacy Badger detected X potential trackers"
The `popup_instructions` message is problematic in a couple of ways right now:
- It doesn't handle languages that treat singular and plural words differently (such as English, for example ... "1 potential trackers").
- Since it translates the second half of a broken-up sentence ("Privacy Badger detected", "X potential trackers ..."), it doesn't handle languages that don't break down sentences the same way. `pb_detected` has the same issue as the first half of this sentence.

### PR DESCRIPTION
**Pull request by mijiturka**
The first commit resolves #1211, and should work on its own if the solution for the other issue isn't ok.

The second two resolve #1443 :
* I'm not sure what the implications are of using locale messages within locale messages (link title starting with i18n_*).
* Moving the href into the messages strips the custom style of the tooltip. I don't know how to get around that. See pictures:
old:
screenshot from 2017-11-13 17-21-21
new: 
screenshot from 2017-11-13 17-21-32

Testing:
* The look of it on Firefox 58.0b1 was fine and the in-browser tests worked.
* I have yet to run any of the python functional tests successfully (on this branch or master)

Happy to change it according to feedback!

### CODE REVIEW

**Comment by ghostwords** [comment]
Thank you! I'll take a look. A couple of GitHub tips:
- You can [prepend issue numbers with certain keywords](https://help.github.com/articles/closing-issues-using-keywords/) to automatically resolve those issues when the PR gets merged.
- No need to use an image hosting service; you can [embed images directly in the description](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by ghostwords** [comment]
To get the fancy tooltip back, you need to restore `class="tooltip"` attribute to the anchor tag.

I am surprised nesting `i18n_` works! Ah, I see, I think it works because we do `i18n_` replacement in two stages, first [here](https://github.com/EFForg/privacybadger/blob/ebd2258416db0979f3de55102b82e8bb8e42509d/src/lib/i18n.js#L24) to replace span contents and then [here](https://github.com/EFForg/privacybadger/blob/ebd2258416db0979f3de55102b82e8bb8e42509d/src/lib/i18n.js#L39) to replace placeholder and title attribute values.

**Comment by ghostwords** [comment]
I see that auto-issue-closing is pretty finicky. You need to use issue numbers `#1211` rather than issue links `https://github.com/EFForg/privacybadger/issues/1211`. I edited the description. You can tell it worked when the keyword before the issue number gets underlined.

**Comment by ghostwords** [comment]
Could you post before and after popup screenshots on a page with no trackers, and also on a page with some trackers? This is a UX change; we should take some time to consider it.

**Comment by mijiturka** [comment]
You're right, I don't know why I missed it! Here are some screenshots:

Popups:
Old:
old-trackers
New:
new-trackers

Old:
old-no-trackers
New:
new-no-track


Old options:
old
New options:
new

**Comment by ghostwords** [comment]
The failing test doesn't have anything to do with this PR. You can force Travis to rerun tests by rewriting and force pushing your most recent commit (rewriting history is OK for branches where you don't have several people committing together): `git commit --amend --noedit && git push -f`.

**Comment by ghostwords** [comment]
"Horray" should be "Hooray". I like this message!

I am not sure I like the "Tracking domains detected so far: XX" formulation though. It seems too robotic; it doesn't seem to fit with the following sentence regarding sliders. Maybe we postpone fixing this message until Transifex adds placeholder support (https://github.com/EFForg/privacybadger/issues/1329#issuecomment-332311249)?

We lost the "potential" part from the message on the options page, but we might want to punt on this message as per above.

**Comment by ghostwords** [comment]
We might also be able to improve the "Privacy Badger has detected ..." message without rephrasing and without using placeholders, but I'm not sure.

**Comment by ghostwords** [comment]
For more ideas, see the "after" screenshot in #1627. We don't need to say "detected 0 trackers" on sites with no third parties, "There are no third party resources on this. Hooray for privacy!" is more to the point.

**Comment by mijiturka** [comment]
Oops, I didn't realise there was an open PR for this! I'm not sure which bits I should keep here now.
I see what you mean about the robotic sound of the message. I personally like the mention of trackers though because it helps people who don't necessarily know what the problem with "third party resources" is.

**Comment by ghostwords** [comment]
The other PR is on hold; there is no problem in covering the same ground here.

**Comment by mijiturka** [comment]
I've now made multiple messages and hide/show them according to the number of trackers from Javascript. It's not the cleanest solution but I thought it could work.
Will do that for the Options page too tomorrow.

**Comment by ghostwords** [comment]
Sounds good! Please post the before/after comparison screenshots too.

**Comment by mijiturka** [comment]
This is ready for review now.

With popups, I run into the same issues that caused #1627 to have the changes to the testing mechanism in it. I don't think there is a way to properly test this without a similar change, because the page that the popup is opened over is not configurable (#1634) - so it's always the PrivacyBadger help page, which has no trackers.

I have modified the test to look for a visible partial occurrence of the word "tracker" in a link, but for now, this only tests the zero-trackers case.

Is there anything I can do to help with the other PR?

New popup messages:
t0
t1
t2

Options tab (I forgot to capture the tooltip on the screenshots but it is there):
o0
o1
o2

**Comment by ghostwords** [comment]
Thank you! Taking a look in a minute.

Could you double-check my Bulgarian translations tweak [here](https://github.com/EFForg/privacybadger/commit/b1c54aa9850968876b4b567555ae4b32e2fc64f8#diff-0abcd516bf3e4c9b63cb7d8ddf18a3af)? [Here](https://github.com/EFForg/privacybadger/commit/b1c54aa9850968876b4b567555ae4b32e2fc64f8#diff-206668ad74de26370ac471b38fdf9bd0) is what changed in the English version.

**Comment by ghostwords** [comment]
I made some followup commits and I'm wondering about the best way to proceed. I'd like us to review my tweaks and keep revising if necessary. Could you give me [permissions to push to your PR](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)?

**Comment by mijiturka** [comment]
I have the "Allow edits from maintainers." checkbox on on this PR, not sure what else I need to do?
Bulgarian translation looks good!

**Comment by ghostwords** [comment]
Nice! OK, I'll get my updates here with screenshots by early next week at the latest. Sorry for the delay.

**Comment by mijiturka** [comment]
No problem! I will try to look at #1706 in the meantime which requires more code-reading anyway.

**Comment by ghostwords** [comment]
## Popup: no trackers

<details><summary>Before</summary>

screenshot from 2017-11-27 13 01 39
</details>

<details><summary>After</summary>

screenshot from 2017-11-27 12 58 47
</details>

**Comment by ghostwords** [comment]
## Popup: one tracker

<details><summary>Before</summary>

screenshot from 2017-11-27 13 02 06
</details>

<details><summary>After</summary>

screenshot from 2017-11-27 12 59 41
</details>

**Comment by ghostwords** [comment]
## Options: no trackers

<details><summary>Before</summary>

screenshot from 2017-11-27 13 01 43
</details>

<details><summary>After</summary>

screenshot from 2017-11-27 12 59 10
</details>

**Comment by ghostwords** [comment]
## Options: one tracker

<details><summary>Before</summary>

screenshot from 2017-11-27 13 02 34
</details>

<details><summary>After</summary>

screenshot from 2017-11-27 12 59 54
</details>

**Comment by ghostwords** [comment]
Commits pushed, screenshots posted. @mijiturka @andresbase Take a look please.

**Comment by mijiturka** [comment]
All looks good to me!

**Comment by andresbase** [comment]
Tested on Windows/Linux/macOS with FF and Chrome latest versions. It looks good, I like it!

Also the text makes sense in English but still need to verify this logic will work for our most popular languages (German, French and Russian)

**Comment by Bisaloo** [comment]
@andresbase, I can confirm this will work just fine in French. In fact, the new text will be much clearer and more grammatically correct.

**Comment by ghostwords** [comment]
Thank you! Merged and synced with Transifex.

**Comment by Urides** [comment]
Hi,

I've noticed that there's still a problem between the singular and plural form in french : 

pluriel pb

With 0 tracker, we should read : 0 traceur potentiel

Thanks

**Pull request merged**
