### PR TITLE
Reduce the entropy value for empty string: 3 -> 1 closes #1399

### LINKED ISSUE #1399: Relax cookie tracking heuristic for empty strings
We probably shouldn't count the following parsed cookie (for `medium.com` from #1397) as a tracker, but we currently do:
```javascript
[
    "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=medium.com; secure; httponly",
    "sid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=medium.com; secure; httponly",
    "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=.medium.com; secure; httponly",
    "sid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=.medium.com; secure; httponly",
    "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; secure; httponly",
    "sid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; secure; httponly",
    "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=.medium.com; secure; httponly",
    "sid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=.medium.com; secure; httponly"
  ]
```
```
All cookies for medium.com deemed low entropy...
But total estimated entropy is 24 bits, so blocking
```

### PR DESCRIPTION
**Pull request by cowlicks**
closes #1399

It seems like the empty string shouldn't have more than one bit of information.

### CODE REVIEW

**Comment by ghostwords** [comment]
How did you go about testing this change?

**Comment by cowlicks** [comment]
@ghostwords paste this in the background page while on this branch:
```javascript
let details = {'requestHeaders': [
  {'name': 'cookie', 'value': "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=medium.com; secure; httponly"},
  {'name': 'cookie', 'value': "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=medium.com; secure; httponly"},
  {'name': 'cookie', 'value': "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=medium.com; secure; httponly"},
  {'name': 'cookie', 'value': "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=medium.com; secure; httponly"},
  {'name': 'cookie', 'value': "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=medium.com; secure; httponly"},
  {'name': 'cookie', 'value': "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=medium.com; secure; httponly"},
  {'name': 'cookie', 'value': "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=medium.com; secure; httponly"},
  {'name': 'cookie', 'value': "uid=; path=/; expires=Thu, 25 May 2017 16:29:49 GMT; domain=medium.com; secure; httponly"},
]};

console.log(HeuristicBlocking.hasCookieTracking(details, 'foo'));
```

**Comment by ghostwords** [comment]
Could you find out why we assigned 3 for empty strings in the first place, and whether 1 makes sense conceptually? I would discuss this with @pde.

**Comment by ghostwords** [comment]
I would also like to understand what effect this change will have in actual browsing. You can add some code that flags cookies with empty strings for review (by printing just those situations to the console, let's say) and then visit a bunch of sites (in a new profile) before and (again in a new profile) after this patch.

**Pull request closed without merging**
