### PR TITLE
add migration to hopefully fix firefox lockup

### PR DESCRIPTION
**Pull request by cooperq**

### CODE REVIEW

**Comment by ghostwords** [comment]
Hmm, can't edit review comments ... Updated link: https://jsfiddle.net/cLs7vq1f/4/

**Comment by ghostwords** [comment]
We speculate that the following part of `migrateLegacyFirefoxData` ends up triggering many thousands of DNT checks (one for every distinct domain that appeared on three or more sites) all at the same time:
```javascript
    // Import snitch map 
    _.each(originFrequency, function(fpDomains, trackingDomain){
      _.each(fpDomains, function(v, firstParty){
        badger.heuristicBlocking.recordPrevalence(
          trackingDomain,
          trackingDomain,
          firstParty
        );
      });
    });
```

**Comment by ghostwords** [comment]
As a followup, we should ...
- Rewrite `checkForDNTPolicy` so that this sort of stampeding becomes impossible. Could try debouncing all calls and sending out DNT requests in batches. This is important because it gets around cases where the user shuts down Privacy Badger for a while, and then comes back to a clumped mass of ready-to-be-checked `actionMap` entries.
- Investigate whether other tweaks are warranted, like whether [`_newActionMapObject`](https://github.com/EFForg/privacybadger/blob/b6681192ba3929d413410b7d9862bb51acb90353/src/storage.js#L298-L305) should initialize with `nextUpdateTime` set to random number of minutes instead of zero. Should `recheckDNTPolicyForDomains` get called more often than once per hour?
- Start adding tests (unit and integration probably) for running common Privacy Badger methods with large amounts of domains/other data to ensure nothing takes too long.

**Comment by alexristich** [comment]
@ghostwords Is this what's causing #1076?

**Comment by ghostwords** [comment]
Probably, I haven't checked though.

**Comment by cooperq** [comment]
@alexristich I suspect it is.

**Pull request merged**
