### PR TITLE
Move extension sources into own folder

### LINKED ISSUE #1241: Privacy Badger local CRX builds are broken
While running `make` / `make travisbuild` locally successfully produces CRX builds, when used with Selenium, these builds end up hanging and timing out ChromeDriver (with an unhelpful error 104 message). The reason being the CRX archive ends up including your `.git` and `node_modules` folders and all the other things that should not go in the actual build, balooning the build to hundreds of megabytes. One workaround is to restore the zip exclusion list, removed in 54d3136:
```diff
diff --git a/scripts/makezip.sh b/scripts/makezip.sh
index eba596d..a7b33b0 100755
--- a/scripts/makezip.sh
+++ b/scripts/makezip.sh
@@ -1,3 +1,3 @@
 VERSION=`grep '"version":' manifest.json | cut -c14- | sed 's/[",[:space:]\n]//g'`
 PREFIX=privacy_badger
-zip -q -r $PREFIX-$VERSION.zip .
+zip -q -r $PREFIX-$VERSION.zip . -x@scripts/zip_exclude.lst
```
While the resulting CRX works with ChromeDriver, it can still include unwanted junk not yet covered by `zip_exclude.lst`.

The real solution I think is to move everything that goes into the actual (distributed or test) build into a dedicated folder. (We should check that git is smart about merging this big move into outstanding pull requests.)

Does Travis currently slurp the git folder into the build? Then resolving this might fix our ongoing sporadic Travis test failures.

This will also resolve (most) development warnings on the Chrome extensions page:
```
There were warnings when trying to install this extension:
Unrecognized manifest key 'applications'.
This extension includes the key file '/home/alexei/Projects/privacybadgerchrome/node_modules/web-ext/node_modules/sign-addon/node_modules/jsonwebtoken/test/rsa-public-key.pem'. You probably don't want to do that.
This extension includes the key file '/home/alexei/Projects/privacybadgerchrome/node_modules/web-ext/node_modules/sign-addon/node_modules/jsonwebtoken/test/priv.pem'. You probably don't want to do that.
This extension includes the key file '/home/alexei/Projects/privacybadgerchrome/node_modules/web-ext/node_modules/sign-addon/node_modules/jsonwebtoken/test/rsa-public.pem'. You probably don't want to do that.
This extension includes the key file '/home/alexei/Projects/privacybadgerchrome/node_modules/web-ext/node_modules/sign-addon/node_modules/jsonwebtoken/test/rsa-private.pem'. You probably don't want to do that.
This extension includes the key file '/home/alexei/Projects/privacybadgerchrome/scripts/dummy-chromium.pem'. You probably don't want to do that.
```

### PR DESCRIPTION
**Pull request by ghostwords**
Fixes #1241. Progress:
- [x] Move sources into `dist/`
- [x] Get unit tests working
- [x] Get functional tests working
- [x] Update release scripts

### CODE REVIEW

**Comment by cowlicks** [comment]
@ghostwords won't this now include qunit in the distributed builds? the `dist/tests/lib/vendor` directory is about 2.3 MB. Which seems kind of significant since the extension itself is only a few MB.

**Comment by ghostwords** [comment]
Good catch! I thought the tests folder would be removed by existing [release build script cleanup](https://github.com/EFForg/privacybadger/blob/8f5fe23af9b91d5297f9bd711689061057060c60/release-utils/make-eff-zip.sh#L16-L18), but missed confirming. It looks like that cleanup code needs to be updated to work with `dist/`.

Unit tests are a special case to the "keep only what is needed for the extension to function in the sources folder" rule, since we want to make them easily accessible during development.

We had a release from the new folder structure yesterday, here are the "only in one but not the other" differences:
````
$ diff -qr privacy_badger-2017.3.22 privacy_badger-2017.3.28 | grep 'Only in'
Only in privacy_badger-2017.3.28/data: dnt-policy.txt
Only in privacy_badger-2017.3.28/_locales: cs
Only in privacy_badger-2017.3.28: tests
Only in privacy_badger-2017.3.22/lib: jsbn.js
Only in privacy_badger-2017.3.22/lib: rsa.js
Only in privacy_badger-2017.3.22/lib: sha1.js
Only in privacy_badger-2017.3.22: LICENSE
```
I'll fix now. File size difference (~0.6 MB):
```
 $ ls -l *.xpi
-rw-rw-r-- 1 alexei alexei 1804211 Mar 29 10:39 privacy_badger-2017.3.22-an+fx.xpi
-rw-rw-r-- 1 alexei alexei 2441632 Mar 29 10:39 privacy_badger-2017.3.28-an+fx-linux.xpi
```

**Comment by ghostwords** [comment]
Here is the other bug found during yesterday's release: 8f5fe23af9b91d5297f9bd711689061057060c60.

**Comment by cooperq** [comment]
I wouldn't even call this a bug since I'm not clear on why pushd and popd didn't work. They should have! But anyway this fixed whatever issue they were having. And you are right about removing tests. We got accepted this time but we should still update the release scripts.  

On March 29, 2017 7:52:15 AM PDT, Alexei <notifications@github.com> wrote:
>Here is the other bug found during yesterday's release:
>8f5fe23af9b91d5297f9bd711689061057060c60.
>
>-- 
>You are receiving this because your review was requested.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/privacybadger/pull/1278#issuecomment-290115211

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ghostwords** [comment]
Must be something about mixing parenthesized commands (subshelling) and `pushd`.

**Comment by ghostwords** [comment]
Ahh, and we failed to actually release Ukrainian translations ... They are [still in the old folder structure](https://github.com/EFForg/privacybadger/tree/8f5fe23af9b91d5297f9bd711689061057060c60/_locales/uk).

**Comment by cowlicks** [comment]
Fwiw I think this is a good case for having the dev dependencies be npm installed. It'll also keep the repo size down,  and make upgrading easier. I don't think the extra step of requiring developers to do a npm install is much to ask.

**Comment by ghostwords** [comment]
Cool, noted. I'd rather not change it now ([previous response](https://github.com/EFForg/privacybadger/pull/1250#issuecomment-289612583)), but let's see how it goes later.

**Pull request merged**
